-- ===================================================
-- 08_demo_seed.sql
-- ===================================================
-- Intentionally empty.
--
-- The previous version inserted fixed accounts directly into auth.users,
-- including reusable password hashes and publicly documented email addresses.
-- Do not seed authentication users in a production migration. Create test
-- accounts only in a non-production Supabase project through the Auth API.