import type { Challenge, Workout, WorkoutItem } from "./gym-types";

const challengeItem = (
  id: string,
  exerciseId: string,
  exerciseName: string,
  sets: number,
  reps: number,
  rest: number,
  notes: string,
): WorkoutItem => ({
  id,
  exerciseId,
  exerciseName,
  sets,
  reps,
  repType: "fixed",
  weight: 0,
  rest,
  notes,
  workingSets: Array.from({ length: sets }, (_, index) => ({
    id: `${id}-set-${index + 1}`,
    setNumber: index + 1,
    weight: 0,
    reps,
    rest,
  })),
});

const runningItem = (
  id: string,
  title: string,
  distanceKm: number,
  rest: number,
  notes: string,
): WorkoutItem => ({
  ...challengeItem(id, "ex-running", title, 1, 1, rest, notes),
  distanceKm,
});

const workout = (id: string, name: string, notes: string, items: WorkoutItem[]): Workout => ({
  id,
  name,
  notes,
  items,
});

const builtInChallenge = (
  id: string,
  title: string,
  description: string,
  category: Challenge["category"],
  difficulty: Challenge["difficulty"],
  durationLabel: string,
  accent: Challenge["accent"],
  sessionName: string,
  sessionNotes: string,
  items: WorkoutItem[],
  nutritionTips?: string[],
): Challenge => {
  const challenge: Challenge = {
    id,
    title,
    description,
    category,
    difficulty,
    durationLabel,
    accent,
    isBuiltIn: true,
    isPublished: true,
    sessions: [workout(`${id}-session`, sessionName, sessionNotes, items)],
  };
  if (nutritionTips) challenge.nutritionTips = nutritionTips;
  return challenge;
};

const shortRunFuel = [
  "בריצה של עד כ־45–60 דקות לרוב לא צריך תדלוק מיוחד במהלך הריצה; שתו לפי צמא.",
  "אם את רעבה, אכלי 30–90 דקות לפני משהו קל ומוכר כמו בננה, טוסט או יוגורט.",
  "אחרי הריצה: ארוחה רגילה עם מקור חלבון ופחמימה בתוך כמה שעות.",
];

const mediumRunFuel = [
  "שעתיים–שלוש לפני הריצה בחרי ארוחה מוכרת עם פחמימה, מעט חלבון ושומן שלא מכביד.",
  "אם הריצה נמשכת יותר משעה, אפשר לתרגל 30–60 גרם פחמימה לשעה — רק עם מוצר שכבר ניסית.",
  "אחרי הריצה: שלבי פחמימה, 20–30 גרם חלבון ונוזלים; אין צורך ב'פיצוי' או בצום.",
];

const longRunFuel = [
  "בערב שלפני ובארוחה 2–4 שעות לפני, העדיפי פחמימות מוכרות וקלות לעיכול. לא מנסים מאכלים חדשים ביום הריצה.",
  "בריצה ארוכה מ־75–90 דקות תרגלי 30–60 גרם פחמימה לשעה, למשל ג׳ל, משקה ספורט או תמרים, יחד עם מים.",
  "אחרי הריצה: בתוך שעה–שעתיים אכלי פחמימה לשיקום מאגרי האנרגיה, חלבון ונוזלים עם מעט מלח לפי הזעה.",
  "הכמות המדויקת תלויה בגודל הגוף, מזג האוויר והקצב; בתחרות או ברגישות רפואית כדאי להתייעץ עם דיאטנית ספורט.",
];

const noSpecialFuel = [
  "זהו אימון גמישות או כוח קצר — אין צורך בתזונת ספורט מיוחדת.",
  "הגיעי hydrated ואכלי במהלך היום ארוחות רגילות עם חלבון, פחמימות, ירקות ושומן איכותי.",
  "אחרי האימון: מים וארוחה רגילה לפי רעב; לא צריך 'לשרוף' או לקזז אוכל.",
];

/**
 * Built-in challenges are intentionally coaching-led: progressive running
 * distances, flexibility goals, and support work that improves consistency.
 * The retired IDs keep old cached catalogs from resurfacing after hydration.
 */
export const RETIRED_BUILT_IN_CHALLENGE_IDS = [
  "challenge-20-10",
  "challenge-30-pushups",
  "challenge-handstand",
  "challenge-pullup",
  "challenge-5k-first",
  "challenge-10k-builder",
  "challenge-100-squats",
  "challenge-50-lunges",
  "challenge-5-minute-plank",
  "challenge-100-pushups",
  "challenge-10-minute-cardio",
  "challenge-full-body-15",
  "challenge-core-trio",
  "challenge-upper-body",
  "challenge-lower-body",
  "challenge-glute-activation",
  "challenge-morning-mobility",
  "challenge-run-walk-30",
  "challenge-10-pullups",
  "challenge-100-mountain-climbers",
] as const;

export const BUILT_IN_CHALLENGES: Challenge[] = [
  builtInChallenge(
    "challenge-run-1k",
    "ריצת 1 ק״מ ראשונה",
    "כניסה רגועה לעולם הריצה: מסיימים קילומטר אחד בקצב שאפשר לדבר בו, בלי לרדוף אחרי השעון.",
    "סבולת",
    "מתחילים",
    "שבועיים",
    "sage",
    "1 ק״מ — היכרות עם הקצב",
    "התחילי ב־5 דקות הליכה קלה. רוצי בקצב שיחה, ובמידת הצורך שלבי הליכה קצרה. המטרה היא לסיים בתחושת יכולת לעוד קצת.",
    [runningItem("challenge-run-1k-main", "ריצה — 1 ק״מ", 1, 180, "מרחק: 1 ק״מ · קצב שיחה · אפשר לשלב הליכה")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-run-3k",
    "3 ק״מ בקצב נוח",
    "בונים רצף ושליטה בקצב עד 3 ק״מ. מתקדמים רק כאשר אפשר לסיים בלי כאב ובלי התרסקות.",
    "סבולת",
    "מתחילים",
    "4 שבועות",
    "lavender",
    "3 ק״מ — ריצה קלה",
    "רוצי את רוב האימון בקצב קל מאוד. אם הנשימה כבדה מדי, האטי או שלבי דקה הליכה; זה חלק מהתוכנית.",
    [runningItem("challenge-run-3k-main", "ריצה — 3 ק״מ", 3, 240, "מרחק: 3 ק״מ · קצב קל · סיום בשליטה")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-run-5k",
    "5 ק״מ ראשונים",
    "מסלול מדורג ל־5 ק״מ עם דגש על התמדה, ריצה קלה ושילוב הליכה כשצריך. לא מודדים הצלחה רק לפי זמן.",
    "סבולת",
    "מתחילים",
    "6 שבועות",
    "sage",
    "5 ק״מ — ריצה ארוכה קלה",
    "פתחי לאט יותר ממה שנדמה לך. אפשר להשתמש בשיטת 9 דקות ריצה ודקה הליכה, או בכל יחס שמאפשר לסיים את כל המרחק.",
    [runningItem("challenge-run-5k-main", "ריצה — 5 ק״מ", 5, 300, "מרחק: 5 ק״מ · קצב שיחה · הליכה קצרה מותרת")],
    mediumRunFuel,
  ),
  builtInChallenge(
    "challenge-run-5k-consistency",
    "5 ק״מ — בונים התמדה",
    "תוכנית למי שכבר מסוגלת להגיע ל־5 ק״מ ורוצה להפוך את הריצה להרגל: ריצה קלה, אימון איכות וריצה ארוכה בהדרגה.",
    "סבולת",
    "ביניים",
    "6 שבועות",
    "peach",
    "5 ק״מ — שבוע ריצה מאוזן",
    "במהלך השבוע שלבי 2–3 ריצות: רובן קלות, ורק אחת מעט מהירה יותר. השאירי לפחות יום קל או מנוחה בין אימונים מאתגרים.",
    [runningItem("challenge-run-5k-consistency-main", "ריצה — 5 ק״מ", 5, 240, "ריצה קלה רציפה; 1 ק״מ אחרון יכול להיות מעט מהיר יותר אם נשארת בשליטה")],
    mediumRunFuel,
  ),
  builtInChallenge(
    "challenge-run-10k",
    "בדרך ל־10 ק״מ",
    "בניית מרחק הדרגתית ל־10 ק״מ, עם רוב האימונים בקצב קל ושבועות התאוששות כדי לאפשר לגוף להסתגל.",
    "סבולת",
    "ביניים",
    "10 שבועות",
    "lavender",
    "10 ק״מ — ריצה ארוכה",
    "רוצי את רוב המרחק בקצב קל. הגדילי את הריצה הארוכה בהדרגה, ושמרי על שבוע הורדה מדי כמה שבועות במקום להעלות עומס ברצף.",
    [runningItem("challenge-run-10k-main", "ריצה — 10 ק״מ", 10, 360, "מרחק: 10 ק״מ · רובו בקצב קל · לא מבחן מהירות")],
    longRunFuel,
  ),
  builtInChallenge(
    "challenge-run-15k",
    "15 ק״מ בביטחון",
    "שלב ביניים לרצות שכבר נוח להן עם 10 ק״מ ורוצות להאריך את הריצה הארוכה בלי להפוך כל אימון למרוץ.",
    "סבולת",
    "מתקדמים",
    "12 שבועות",
    "sand",
    "15 ק״מ — סבולת ארוכה",
    "שמרי על קצב קל מאוד בתחילת הריצה. תרגלי שתייה ותדלוק באימונים, והפסיקי במקרה של כאב חד, סחרחורת או שינוי בצעד.",
    [runningItem("challenge-run-15k-main", "ריצה — 15 ק״מ", 15, 420, "מרחק: 15 ק״מ · קצב קל ויציב · תדלוק מתורגל")],
    longRunFuel,
  ),
  builtInChallenge(
    "challenge-run-21k",
    "חצי מרתון — בסיס",
    "מסלול מתקדם לבניית בסיס לחצי מרתון. מיועד למי שכבר רצה 10–15 ק״מ ומסוגלת להתאמן באופן עקבי.",
    "סבולת",
    "מתקדמים",
    "16 שבועות",
    "peach",
    "21 ק״מ — ריצה ארוכה מתוכננת",
    "אל תתחילי מהיעד המלא אם עדיין אין בסיס. שלבי ריצות קלות, אימון איכות, מנוחה ושבועות הורדה; במרחק כזה עדיפות להכוונה אישית ממאמן.",
    [runningItem("challenge-run-21k-main", "ריצה — 21 ק״מ", 21, 480, "יעד מתקדם: 21 ק״מ · קצב שמרני · תדלוק ושתייה מתורגלים")],
    longRunFuel,
  ),
  builtInChallenge(
    "challenge-run-walk-30",
    "ריצה־הליכה 30 דקות",
    "אימון כניסה נגיש לבניית הרגל אירובי: מקטעי ריצה קלים עם הליכה מתוכננת, במקום להילחם בעייפות.",
    "סבולת",
    "מתחילים",
    "4 שבועות",
    "peach",
    "ריצה־הליכה — 30 דקות",
    "בצעי 6 סבבים של 3 דקות ריצה ו־2 דקות הליכה. אפשר להאט את הריצה; המטרה היא להישאר בתנועה ברוגע.",
    [challengeItem("challenge-run-walk-30-main", "ex-running", "ריצה והליכה", 6, 60, 30, "6 סבבים: 3 דקות ריצה ו־2 דקות הליכה · סך הכול 30 דקות")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-run-intervals",
    "אינטרוולים 400 מטר",
    "אימון איכות לרצות שכבר רצות באופן עקבי: מקטעים קצרים ומהירים עם התאוששות מלאה, בלי להפוך כל ריצה למבחן.",
    "עצימות",
    "ביניים",
    "6 שבועות",
    "lavender",
    "400 מטר — מהירות בשליטה",
    "אחרי חימום של 10–15 דקות בצעי 6×400 מטר בקצב מהיר אך נשלט, עם 200 מטר הליכה או ריצה קלה בין המקטעים. סיימי בשחרור קל.",
    [challengeItem("challenge-run-intervals-main", "ex-running", "ריצה מהירה — 400 מטר", 6, 400, 120, "6×400 מטר · התאוששות של 200 מטר בין המקטעים · לא ספרינט")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-run-hills",
    "עליות לרצים",
    "מחזקים כוח ריצה וטכניקה דרך עליות קצרות. איכות הצעד והחזרה הבטוחה למטה חשובות יותר מהקצב.",
    "עצימות",
    "ביניים",
    "5 שבועות",
    "sand",
    "עליות — כוח ריצה",
    "אחרי חימום בצעי 8 עליות של 45–60 שניות במאמץ חזק אך נשלט. רדי בהליכה או בריצה קלה, ולעולם אל תוותרי על חימום.",
    [challengeItem("challenge-run-hills-main", "ex-running", "ריצת עלייה", 8, 60, 60, "8 מקטעי עלייה של 45–60 שניות · התאוששות בירידה · יציבה זקופה")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-flex-foundation",
    "גמישות מהבסיס",
    "שגרת גמישות בטוחה לכל הגוף: נשימה, טווח הדרגתי והחזקות רגועות במקום משיכות חדות.",
    "מיומנות",
    "מתחילים",
    "4 שבועות",
    "sage",
    "גמישות — בסיס יומי",
    "החזיקי כל תנוחה 30–45 שניות, נשמי רגיל וצאי ממנה לאט. מתח עדין הוא בסדר; כאב חד או נימול אינם יעד.",
    [
      challengeItem("challenge-flex-foundation-hips", "ex-squat", "פתיחת ירכיים", 2, 40, 20, "40 שניות לכל צד"),
      challengeItem("challenge-flex-foundation-hamstrings", "ex-squat", "מתיחת המסטרינג", 2, 40, 20, "40 שניות לכל צד · גב ארוך"),
      challengeItem("challenge-flex-foundation-shoulders", "ex-plank", "פתיחת כתפיים", 2, 30, 20, "30 שניות · נשימה רגועה"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-front-split",
    "מסלול לשפגאט קדמי",
    "מסלול הדרגתי לשיפור הטווח בשפגאט קדמי דרך כופפי ירך, המסטרינג ושליטה באגן. המטרה היא התקדמות, לא בכוח להגיע לרצפה.",
    "מיומנות",
    "ביניים",
    "12 שבועות",
    "peach",
    "שפגאט קדמי — תרגול",
    "חממי 5–10 דקות לפני מתיחות עמוקות. בצעי 3 סבבים לכל צד, עצרי 2–3 ס״מ לפני כאב, ואל תפעילי לחץ חיצוני כדי לרדת עמוק יותר.",
    [
      challengeItem("challenge-front-split-lunge", "ex-squat", "מתיחת מכרע לכופפי הירך", 3, 45, 20, "45 שניות לכל צד · אגן אסוף"),
      challengeItem("challenge-front-split-hamstring", "ex-squat", "מתיחת המסטרינג", 3, 45, 20, "45 שניות לכל צד · ברך יכולה להיות מעט כפופה"),
      challengeItem("challenge-front-split-hold", "ex-squat", "שפגאט קדמי נתמך", 3, 30, 30, "30 שניות לכל צד · תמיכה בבלוקים או בכיסא"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-middle-split",
    "מסלול לשפגאט אמצעי",
    "עבודה מתונה על מקרבי הירך, ירכיים ושליטה בטווח לשפגאט אמצעי. מתקדמים לאט במיוחד ולא דוחפים דרך כאב במפשעה.",
    "מיומנות",
    "מתקדמים",
    "16 שבועות",
    "lavender",
    "שפגאט אמצעי — טווח ושליטה",
    "חממי היטב לפני התרגול. בצעי תנועה דינמית תחילה, אחר כך החזקות של 30–45 שניות, ושמרי על נשימה ותמיכה בידיים.",
    [
      challengeItem("challenge-middle-split-adductor", "ex-squat", "מתיחת מקרבים בישיבה", 3, 40, 20, "40 שניות · גב ארוך ובלי קפיצות"),
      challengeItem("challenge-middle-split-frog", "ex-squat", "מתיחת צפרדע", 3, 35, 25, "35 שניות · טווח שלא מכאיב במפשעה"),
      challengeItem("challenge-middle-split-hold", "ex-squat", "שפגאט אמצעי נתמך", 3, 25, 30, "25 שניות · ידיים על הרצפה ותנועה איטית"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-hip-opening",
    "פתיחת ירכיים",
    "רצף קצר לשיפור תנועתיות הירך והפחתת תחושת נוקשות מישיבה. מתאים גם לפני ריצה קלה, בלי להפוך מתיחה לחימום היחיד.",
    "מיומנות",
    "מתחילים",
    "4 שבועות",
    "sand",
    "ירכיים — תנועתיות",
    "עברי בין התרגילים בתנועה איטית. לפני אימון מהיר העדיפי תנועות דינמיות; את ההחזקות העמוקות בצעי בסוף האימון או בנפרד.",
    [
      challengeItem("challenge-hip-opening-90", "ex-squat", "מעברי 90/90", 2, 8, 20, "8 מעברים איטיים לכל צד"),
      challengeItem("challenge-hip-opening-lunge", "ex-squat", "מכרע עם הטיית אגן", 2, 40, 20, "40 שניות לכל צד"),
      challengeItem("challenge-hip-opening-pigeon", "ex-squat", "יונה נתמכת", 2, 40, 20, "40 שניות לכל צד · תמיכה לפי הצורך"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-runner-mobility",
    "מוביליטי לרצים",
    "שגרת מוביליטי לקרסוליים, ירכיים ועמוד השדרה שמסייעת להרגיש מוכנים לריצה. היא משלימה אימון ואינה מחליפה חיזוק או מנוחה.",
    "מיומנות",
    "מתחילים",
    "4 שבועות",
    "sage",
    "מוביליטי — לפני ואחרי ריצה",
    "לפני ריצה בצעי 5 דקות תנועה דינמית; אחרי הריצה עברי להחזקות רגועות. אל תנסי לפתור כאב חוזר באמצעות מתיחה בלבד.",
    [
      challengeItem("challenge-runner-mobility-ankle", "ex-squat", "מוביליטי קרסול", 2, 10, 20, "10 חזרות לכל צד · עקב נשאר מחובר"),
      challengeItem("challenge-runner-mobility-hip", "ex-squat", "מכרע דינמי", 2, 8, 20, "8 חזרות לכל צד"),
      challengeItem("challenge-runner-mobility-spine", "ex-plank", "סיבוב בית חזה", 2, 8, 20, "8 חזרות לכל צד · נשימה מלאה"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-hamstrings",
    "המסטרינג וטווח תנועה",
    "שיפור הדרגתי של טווח המסטרינג עם דגש על שליטה באגן, גב ארוך והבדל בין מתיחה טובה לכאב עצבי.",
    "מיומנות",
    "מתחילים",
    "4 שבועות",
    "peach",
    "המסטרינג — שליטה",
    "עשי חימום קל לפני המתיחות. שמרי את הברך רכה, ואל תדחפי את הראש לברך כדי 'להעמיק'.",
    [
      challengeItem("challenge-hamstrings-good-morning", "ex-squat", "כפיפת ירך ללא משקל", 3, 10, 30, "10 חזרות איטיות · גב נייטרלי"),
      challengeItem("challenge-hamstrings-stretch", "ex-squat", "מתיחת המסטרינג", 3, 45, 20, "45 שניות לכל צד · בלי קפיצות"),
      challengeItem("challenge-hamstrings-active", "ex-squat", "הרמת רגל אקטיבית", 3, 8, 30, "8 חזרות לכל צד · טווח בשליטה"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-runner-core",
    "ליבה לרצים",
    "חיזוק ליבה שמטרתו לשמור על יציבה וקצב כשהעייפות מגיעה, בלי להפוך את האימון לתחרות שריפת בטן.",
    "כוח",
    "ביניים",
    "6 שבועות",
    "lavender",
    "ליבה — יציבות לריצה",
    "בצעי 3 סבבים, עם נשימה רציפה. אם הגב מתחיל להתקשת, הקטיני טווח או עברי לגרסה קלה יותר.",
    [
      challengeItem("challenge-runner-core-plank", "ex-plank", "פלאנק", 3, 35, 45, "35 שניות · צלעות ואגן בשליטה"),
      challengeItem("challenge-runner-core-dead-bug", "ex-plank", "דד באג", 3, 10, 45, "10 לכל צד · גב תחתון יציב"),
      challengeItem("challenge-runner-core-side", "ex-plank", "פלאנק צידי", 3, 25, 45, "25 שניות לכל צד"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-runner-glutes",
    "ישבן וייצוב לרצים",
    "אימון משלים לרצים לחיזוק ישבן, ירך צדית ויציבות חד־רגלית. עובדים בטווח שנשאר נקי ולא רודפים אחרי משקל.",
    "כוח",
    "מתחילים",
    "6 שבועות",
    "sand",
    "ישבן — יציבות",
    "בצעי 3 סבבים, עם שליטה בירידה. כאב חד בברך, בירך או בגב הוא סימן לעצור ולבחון את התרגיל.",
    [
      challengeItem("challenge-runner-glutes-bridge", "ex-squat", "גשר ישבן", 3, 12, 45, "12 חזרות עם עצירה של 2 שניות למעלה"),
      challengeItem("challenge-runner-glutes-step", "ex-squat", "עלייה למדרגה", 3, 8, 60, "8 לכל רגל · ברך בקו כף הרגל"),
      challengeItem("challenge-runner-glutes-single", "ex-squat", "סקוואט חד־רגלי נתמך", 3, 6, 60, "6 לכל צד · להחזיק תמיכה"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-strength-foundation",
    "כוח בסיסי פונקציונלי",
    "אימון כוח מאוזן למי שרוצה בסיס שימושי: דחיפה, רגליים, משיכה וליבה, עם מרווח לפני כשל.",
    "כוח",
    "מתחילים",
    "6 שבועות",
    "sage",
    "כוח — בסיס לכל הגוף",
    "השאירי 2–3 חזרות ברזרבה. איכות ותדירות קבועה חשובות יותר מהעמסת משקל מהירה.",
    [
      challengeItem("challenge-strength-foundation-squat", "ex-squat", "סקוואט", 3, 10, 75, "10 חזרות בטווח נוח"),
      challengeItem("challenge-strength-foundation-push", "ex-pushup", "שכיבות סמיכה", 3, 8, 75, "8 חזרות · אפשר שיפוע"),
      challengeItem("challenge-strength-foundation-pull", "ex-pullup", "משיכה / חתירה", 3, 6, 75, "6 חזרות · גומייה או וריאציה מסייעת"),
      challengeItem("challenge-strength-foundation-core", "ex-plank", "פלאנק", 3, 30, 45, "30 שניות"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-active-recovery",
    "התאוששות אקטיבית",
    "יום תנועה קל שמחזיר זרימה לגוף בלי להוסיף עומס: הליכה, מוביליטי ונשימה. זה חלק מהאימון, לא אימון שנכשל.",
    "מיומנות",
    "מתחילים",
    "3 שבועות",
    "sand",
    "התאוששות — תנועה קלה",
    "שמרי על מאמץ נמוך ויכולת לדבר במשפטים שלמים. אם העייפות עמוקה או יש כאב, בחרי מנוחה מלאה.",
    [
      challengeItem("challenge-active-recovery-walk", "ex-running", "הליכה קלה", 1, 20, 60, "20 דקות בקצב רגוע"),
      challengeItem("challenge-active-recovery-hips", "ex-squat", "מוביליטי ירכיים", 2, 8, 20, "8 מעברים איטיים לכל צד"),
      challengeItem("challenge-active-recovery-breath", "ex-plank", "נשימה ומתיחה", 2, 60, 20, "דקה של נשימה רגועה ומתיחה עדינה"),
    ],
    noSpecialFuel,
  ),
];

export function cloneChallenge(challenge: Challenge): Challenge {
  const clone: Challenge = {
    ...challenge,
    id: challenge.id,
    sessions: challenge.sessions.map((session) => ({
      ...session,
      items: session.items.map((item) => {
        const copy = { ...item };
        if (item.workingSets) copy.workingSets = item.workingSets.map((set) => ({ ...set }));
        return copy;
      }),
    })),
  };
  if (challenge.nutritionTips) clone.nutritionTips = [...challenge.nutritionTips];
  return clone;
}