import type { Challenge, Workout, WorkoutItem } from "./gym-types";

const challengeItem = (
  id: string,
  exerciseId: string,
  exerciseName: string,
  sets: number,
  reps: number,
  rest: number,
  notes: string,
): WorkoutItem => ({
  id,
  exerciseId,
  exerciseName,
  sets,
  reps,
  repType: "fixed",
  weight: 0,
  rest,
  notes,
  workingSets: Array.from({ length: sets }, (_, index) => ({
    id: `${id}-set-${index + 1}`,
    setNumber: index + 1,
    weight: 0,
    reps,
    rest,
  })),
});

const runningItem = (
  id: string,
  title: string,
  distanceKm: number,
  rest: number,
  notes: string,
): WorkoutItem => ({
  ...challengeItem(id, "ex-running", title, 1, 1, rest, notes),
  distanceKm,
});

const workout = (id: string, name: string, notes: string, items: WorkoutItem[]): Workout => ({
  id,
  name,
  notes,
  items,
});

const builtInChallenge = (
  id: string,
  title: string,
  description: string,
  category: Challenge["category"],
  difficulty: Challenge["difficulty"],
  durationLabel: string,
  accent: Challenge["accent"],
  sessionName: string,
  sessionNotes: string,
  items: WorkoutItem[],
  nutritionTips?: string[],
): Challenge => {
  const challenge: Challenge = {
    id,
    title,
    description,
    category,
    difficulty,
    durationLabel,
    accent,
    isBuiltIn: true,
    isPublished: true,
    sessions: [workout(`${id}-session`, sessionName, sessionNotes, items)],
  };
  if (nutritionTips) challenge.nutritionTips = nutritionTips;
  return challenge;
};

const shortRunFuel = [
  "עד שעה של ריצה? בדרך כלל לא צריך להסתבך עם תדלוק תוך כדי. פשוט שותים לפי הצמא.",
  "אם את רעבה, תאכלי 30–90 דקות לפני משהו קל שאת כבר מכירה: בננה, טוסט או יוגורט.",
  "אחרי הריצה תאכלי רגיל: משהו עם חלבון ומשהו עם פחמימה, וזהו.",
];

const mediumRunFuel = [
  "שעתיים–שלוש לפני הריצה תאכלי ארוחה מוכרת עם פחמימה וקצת חלבון, בלי משהו כבד שיעשה בלגן בבטן.",
  "אם הריצה עוברת שעה, אפשר לתרגל 30–60 גרם פחמימה לשעה — ג׳ל, תמרים או משקה שכבר ניסית.",
  "אחרי הריצה: פחמימה, 20–30 גרם חלבון ומים. לא צריך לפצות ולא צריך לצום.",
];

const longRunFuel = [
  "בערב שלפני ובארוחה 2–4 שעות לפני, לכי על פחמימות מוכרות וקלות לעיכול. ביום הריצה לא מנסים מאכלים חדשים.",
  "ריצה של 75–90 דקות ומעלה? תתרגלי 30–60 גרם פחמימה לשעה — ג׳ל, משקה ספורט או תמרים — עם מים.",
  "אחרי הריצה, בתוך שעה–שעתיים, תאכלי פחמימה, חלבון ותשתִי. אם הזעת הרבה, גם קצת מלח יכול לעזור.",
  "הכמות שמתאימה לך תלויה בגוף, בחום ובקצב. לקראת מרוץ או אם יש רגישות רפואית, שווה לדבר עם דיאטנית ספורט.",
];

const noSpecialFuel = [
  "זה אימון קצר של גמישות או כוח, אז אין צורך בתזונת ספורט מיוחדת.",
  "תגיעי עם מים ותאכלי במהלך היום רגיל: חלבון, פחמימות, ירקות ושומן טוב.",
  "אחרי האימון: מים וארוחה לפי הרעב. לא צריך 'לשרוף' ולא צריך לקזז.",
];

/**
 * Built-in challenges are intentionally coaching-led: progressive running
 * distances, flexibility goals, and support work that improves consistency.
 * The retired IDs keep old cached catalogs from resurfacing after hydration.
 */
export const RETIRED_BUILT_IN_CHALLENGE_IDS = [
  "challenge-20-10",
  "challenge-30-pushups",
  "challenge-handstand",
  "challenge-pullup",
  "challenge-5k-first",
  "challenge-10k-builder",
  "challenge-100-squats",
  "challenge-50-lunges",
  "challenge-5-minute-plank",
  "challenge-100-pushups",
  "challenge-10-minute-cardio",
  "challenge-full-body-15",
  "challenge-core-trio",
  "challenge-upper-body",
  "challenge-lower-body",
  "challenge-glute-activation",
  "challenge-morning-mobility",
  "challenge-run-walk-30",
  "challenge-10-pullups",
  "challenge-100-mountain-climbers",
] as const;

export const BUILT_IN_CHALLENGES: Challenge[] = [
  builtInChallenge(
    "challenge-run-1k",
    "ריצת 1 ק״מ ראשונה",
    "מתחילות בקטן: קילומטר אחד בקצב שאפשר לדבר בו, בלי לרדוף אחרי השעון.",
    "סבולת",
    "מתחילים",
    "שבועיים",
    "sage",
    "1 ק״מ — היכרות עם הקצב",
    "תתחילי ב־5 דקות הליכה קלה. תרוצי בקצב שיחה, ואם צריך תשלבי הליכה. המטרה היא לסיים ולהרגיש שיש לך עוד קצת.",
    [runningItem("challenge-run-1k-main", "ריצה — 1 ק״מ", 1, 180, "מרחק: 1 ק״מ · קצב שיחה · אפשר לשלב הליכה")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-run-3k",
    "3 ק״מ בקצב נוח",
    "בונות לאט את הדרך ל־3 ק״מ, בלי להיחנק ובלי להתרסק בסוף.",
    "סבולת",
    "מתחילים",
    "4 שבועות",
    "lavender",
    "3 ק״מ — ריצה קלה",
    "את רוב האימון תעשי בקצב קל. אם הנשימה כבדה מדי, תאטי או תשלבי דקה הליכה — זה לגמרי חלק מהתוכנית.",
    [runningItem("challenge-run-3k-main", "ריצה — 3 ק״מ", 3, 240, "מרחק: 3 ק״מ · קצב קל · סיום בשליטה")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-run-5k",
    "5 ק״מ ראשונים",
    "דרך פשוטה להגיע ל־5 ק״מ: ריצות קלות, קצת הליכה כשצריך, ובעיקר התמדה. הזמן פחות חשוב כרגע.",
    "סבולת",
    "מתחילים",
    "6 שבועות",
    "sage",
    "5 ק״מ — ריצה ארוכה קלה",
    "תפתחי יותר לאט ממה שנדמה לך. אפשר לעשות 9 דקות ריצה ודקה הליכה, או כל יחס שעוזר לך לסיים את המרחק בכיף.",
    [runningItem("challenge-run-5k-main", "ריצה — 5 ק״מ", 5, 300, "מרחק: 5 ק״מ · קצב שיחה · הליכה קצרה מותרת")],
    mediumRunFuel,
  ),
  builtInChallenge(
    "challenge-run-5k-consistency",
    "5 ק״מ — בונים התמדה",
    "כבר מגיעה ל־5 ק״מ ורוצה שזה יהפוך להרגל? כאן משלבות ריצה קלה, אימון איכות וריצה ארוכה — בלי להגזים.",
    "סבולת",
    "ביניים",
    "6 שבועות",
    "peach",
    "5 ק״מ — שבוע ריצה מאוזן",
    "בשבוע הזה תשלבי 2–3 ריצות: רובן קלות, ורק אחת קצת יותר מהירה. תשאירי יום קל או מנוחה בין אימונים קשים.",
    [runningItem("challenge-run-5k-consistency-main", "ריצה — 5 ק״מ", 5, 240, "ריצה קלה רציפה; 1 ק״מ אחרון יכול להיות מעט מהיר יותר אם נשארת בשליטה")],
    mediumRunFuel,
  ),
  builtInChallenge(
    "challenge-run-10k",
    "בדרך ל־10 ק״מ",
    "בדרך ל־10 ק״מ עולים בהדרגה, רוב הריצות נשארות קלות, ומשאירים מקום גם להתאוששות.",
    "סבולת",
    "ביניים",
    "10 שבועות",
    "lavender",
    "10 ק״מ — ריצה ארוכה",
    "את רוב המרחק תרוצי קל. תעלי את הריצה הארוכה בהדרגה, וכל כמה שבועות תני לגוף שבוע קצת יותר רגוע.",
    [runningItem("challenge-run-10k-main", "ריצה — 10 ק״מ", 10, 360, "מרחק: 10 ק״מ · רובו בקצב קל · לא מבחן מהירות")],
    longRunFuel,
  ),
  builtInChallenge(
    "challenge-run-15k",
    "15 ק״מ בביטחון",
    "כבר נוח לך עם 10 ק״מ ובא לך להאריך? זה השלב לבנות 15 ק״מ בלי להפוך כל אימון למרוץ.",
    "סבולת",
    "מתקדמים",
    "12 שבועות",
    "sand",
    "15 ק״מ — סבולת ארוכה",
    "תתחילי ממש קל. תתרגלי שתייה ותדלוק כבר באימונים, ותעצרי אם יש כאב חד, סחרחורת או שינוי בצעד.",
    [runningItem("challenge-run-15k-main", "ריצה — 15 ק״מ", 15, 420, "מרחק: 15 ק״מ · קצב קל ויציב · תדלוק מתורגל")],
    longRunFuel,
  ),
  builtInChallenge(
    "challenge-run-21k",
    "חצי מרתון — בסיס",
    "הכנה רצינית לחצי מרתון, למי שכבר רצה 10–15 ק״מ ויכולה להתאמן בעקביות.",
    "סבולת",
    "מתקדמים",
    "16 שבועות",
    "peach",
    "21 ק״מ — ריצה ארוכה מתוכננת",
    "לא קופצות ישר ל־21 ק״מ אם אין בסיס. משלבות ריצות קלות, אימון איכות, מנוחה ושבועות רגועים. במרחק כזה ממש שווה ליווי של מאמן.",
    [runningItem("challenge-run-21k-main", "ריצה — 21 ק״מ", 21, 480, "יעד מתקדם: 21 ק״מ · קצב שמרני · תדלוק ושתייה מתורגלים")],
    longRunFuel,
  ),
  builtInChallenge(
    "challenge-run-walk-30",
    "ריצה־הליכה 30 דקות",
    "אימון כניסה נוח לבניית הרגל: ריצה קלה והליכה מתוכננת, בלי להילחם בעייפות.",
    "סבולת",
    "מתחילים",
    "4 שבועות",
    "peach",
    "ריצה־הליכה — 30 דקות",
    "תעשי 6 סבבים של 3 דקות ריצה ו־2 דקות הליכה. אפשר גם להאט — המטרה היא להישאר בתנועה ולהרגיש טוב.",
    [challengeItem("challenge-run-walk-30-main", "ex-running", "ריצה והליכה", 6, 60, 30, "6 סבבים: 3 דקות ריצה ו־2 דקות הליכה · סך הכול 30 דקות")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-run-intervals",
    "אינטרוולים 400 מטר",
    "אימון איכות למי שכבר רצה קבוע: קטעים קצרים ומהירים עם התאוששות טובה, בלי להפוך כל ריצה למבחן.",
    "עצימות",
    "ביניים",
    "6 שבועות",
    "lavender",
    "400 מטר — מהירות בשליטה",
    "אחרי חימום של 10–15 דקות תעשי 6×400 מטר בקצב מהיר אבל בשליטה, עם 200 מטר הליכה או ריצה קלה בין הקטעים. בסוף תעשי שחרור קל.",
    [challengeItem("challenge-run-intervals-main", "ex-running", "ריצה מהירה — 400 מטר", 6, 400, 120, "6×400 מטר · התאוששות של 200 מטר בין המקטעים · לא ספרינט")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-run-hills",
    "עליות לרצים",
    "מחזקות את הריצה דרך עליות קצרות. הצעד והחזרה הבטוחה למטה חשובים יותר מהקצב.",
    "עצימות",
    "ביניים",
    "5 שבועות",
    "sand",
    "עליות — כוח ריצה",
    "אחרי חימום תעשי 8 עליות של 45–60 שניות, חזק אבל בשליטה. תרדי בהליכה או בריצה קלה — וחימום לא מדלגים.",
    [challengeItem("challenge-run-hills-main", "ex-running", "ריצת עלייה", 8, 60, 60, "8 מקטעי עלייה של 45–60 שניות · התאוששות בירידה · יציבה זקופה")],
    shortRunFuel,
  ),
  builtInChallenge(
    "challenge-flex-foundation",
    "גמישות מהבסיס",
    "עשר דקות לפתוח את הגוף: נושמות, נכנסות לטווח בהדרגה ולא מושכות בכוח.",
    "מיומנות",
    "מתחילים",
    "4 שבועות",
    "sage",
    "גמישות — בסיס יומי",
    "תחזיקי כל תנוחה 30–45 שניות, תנשמי רגיל ותצאי לאט. מתיחה עדינה זה טוב; כאב חד או נימול — עוצרות.",
    [
      challengeItem("challenge-flex-foundation-hips", "ex-squat", "פתיחת ירכיים", 2, 40, 20, "40 שניות לכל צד"),
      challengeItem("challenge-flex-foundation-hamstrings", "ex-squat", "מתיחת המסטרינג", 2, 40, 20, "40 שניות לכל צד · גב ארוך"),
      challengeItem("challenge-flex-foundation-shoulders", "ex-plank", "פתיחת כתפיים", 2, 30, 20, "30 שניות · נשימה רגועה"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-front-split",
    "מסלול לשפגאט קדמי",
    "עובדות בהדרגה על שפגאט קדמי דרך הירכיים והמסטרינג. לא צריך להגיע לרצפה עכשיו — כל טווח קטן נחשב.",
    "מיומנות",
    "ביניים",
    "12 שבועות",
    "peach",
    "שפגאט קדמי — תרגול",
    "תחממי 5–10 דקות לפני שנכנסות עמוק. תעשי 3 סבבים לכל צד, תעצרי לפני כאב ואל תנסי לדחוף את עצמך למטה.",
    [
      challengeItem("challenge-front-split-lunge", "ex-squat", "מתיחת מכרע לכופפי הירך", 3, 45, 20, "45 שניות לכל צד · אגן אסוף"),
      challengeItem("challenge-front-split-hamstring", "ex-squat", "מתיחת המסטרינג", 3, 45, 20, "45 שניות לכל צד · ברך יכולה להיות מעט כפופה"),
      challengeItem("challenge-front-split-hold", "ex-squat", "שפגאט קדמי נתמך", 3, 30, 30, "30 שניות לכל צד · תמיכה בבלוקים או בכיסא"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-middle-split",
    "מסלול לשפגאט אמצעי",
    "עובדות על מקרבי הירך ועל הטווח לשפגאט אמצעי. כאן במיוחד לא ממהרות ולא דוחפות דרך כאב במפשעה.",
    "מיומנות",
    "מתקדמים",
    "16 שבועות",
    "lavender",
    "שפגאט אמצעי — טווח ושליטה",
    "תחממי טוב לפני. קודם תנועה, אחר כך החזקות של 30–45 שניות. הידיים יכולות לעזור — אין סיבה להילחם ברצפה.",
    [
      challengeItem("challenge-middle-split-adductor", "ex-squat", "מתיחת מקרבים בישיבה", 3, 40, 20, "40 שניות · גב ארוך ובלי קפיצות"),
      challengeItem("challenge-middle-split-frog", "ex-squat", "מתיחת צפרדע", 3, 35, 25, "35 שניות · טווח שלא מכאיב במפשעה"),
      challengeItem("challenge-middle-split-hold", "ex-squat", "שפגאט אמצעי נתמך", 3, 25, 30, "25 שניות · ידיים על הרצפה ותנועה איטית"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-hip-opening",
    "פתיחת ירכיים",
    "רצף קצר לפתוח ירכיים אחרי ישיבה. מעולה לפני ריצה קלה, אבל לא מחליף חימום אמיתי.",
    "מיומנות",
    "מתחילים",
    "4 שבועות",
    "sand",
    "ירכיים — תנועתיות",
    "תעברי לאט בין התרגילים. לפני אימון מהיר תעשי תנועה דינמית; את המתיחות העמוקות תשמרי לסוף או ליום נפרד.",
    [
      challengeItem("challenge-hip-opening-90", "ex-squat", "מעברי 90/90", 2, 8, 20, "8 מעברים איטיים לכל צד"),
      challengeItem("challenge-hip-opening-lunge", "ex-squat", "מכרע עם הטיית אגן", 2, 40, 20, "40 שניות לכל צד"),
      challengeItem("challenge-hip-opening-pigeon", "ex-squat", "יונה נתמכת", 2, 40, 20, "40 שניות לכל צד · תמיכה לפי הצורך"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-runner-mobility",
    "מוביליטי לרצים",
    "כמה דקות לקרסוליים, לירכיים ולגב כדי להרגיש יותר מוכנה לריצה. זה משלים אימון — לא מחליף כוח או מנוחה.",
    "מיומנות",
    "מתחילים",
    "4 שבועות",
    "sage",
    "מוביליטי — לפני ואחרי ריצה",
    "לפני ריצה תעשי 5 דקות תנועה דינמית; אחרי הריצה אפשר להישאר במתיחות רגועות. כאב שחוזר לא פותרים רק במתיחה.",
    [
      challengeItem("challenge-runner-mobility-ankle", "ex-squat", "מוביליטי קרסול", 2, 10, 20, "10 חזרות לכל צד · עקב נשאר מחובר"),
      challengeItem("challenge-runner-mobility-hip", "ex-squat", "מכרע דינמי", 2, 8, 20, "8 חזרות לכל צד"),
      challengeItem("challenge-runner-mobility-spine", "ex-plank", "סיבוב בית חזה", 2, 8, 20, "8 חזרות לכל צד · נשימה מלאה"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-hamstrings",
    "המסטרינג וטווח תנועה",
    "פותחות טווח במסטרינג בהדרגה, עם אגן בשליטה וגב ארוך. לומדות להבדיל בין מתיחה טובה לכאב עצבי.",
    "מיומנות",
    "מתחילים",
    "4 שבועות",
    "peach",
    "המסטרינג — שליטה",
    "תעשי חימום קצר לפני המתיחות. הברך נשארת קצת רכה, ולא דוחפים את הראש לברך כדי 'להעמיק'.",
    [
      challengeItem("challenge-hamstrings-good-morning", "ex-squat", "כפיפת ירך ללא משקל", 3, 10, 30, "10 חזרות איטיות · גב נייטרלי"),
      challengeItem("challenge-hamstrings-stretch", "ex-squat", "מתיחת המסטרינג", 3, 45, 20, "45 שניות לכל צד · בלי קפיצות"),
      challengeItem("challenge-hamstrings-active", "ex-squat", "הרמת רגל אקטיבית", 3, 8, 30, "8 חזרות לכל צד · טווח בשליטה"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-runner-core",
    "ליבה לרצים",
    "מחזקות ליבה כדי להישאר יציבות גם כשהריצה מתעייפת, בלי להפוך את זה לתחרות מי שורפת יותר בבטן.",
    "כוח",
    "ביניים",
    "6 שבועות",
    "lavender",
    "ליבה — יציבות לריצה",
    "תעשי 3 סבבים ותמשיכי לנשום. אם הגב מתחיל להתקשת, תקטיני טווח או תעברי לגרסה קלה יותר.",
    [
      challengeItem("challenge-runner-core-plank", "ex-plank", "פלאנק", 3, 35, 45, "35 שניות · צלעות ואגן בשליטה"),
      challengeItem("challenge-runner-core-dead-bug", "ex-plank", "דד באג", 3, 10, 45, "10 לכל צד · גב תחתון יציב"),
      challengeItem("challenge-runner-core-side", "ex-plank", "פלאנק צידי", 3, 25, 45, "25 שניות לכל צד"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-runner-glutes",
    "ישבן וייצוב לרצים",
    "אימון משלים לרצים לחיזוק ישבן, ירך צדית ויציבות על רגל אחת. עובדות נקי ולא רודפות אחרי משקל.",
    "כוח",
    "מתחילים",
    "6 שבועות",
    "sand",
    "ישבן — יציבות",
    "תעשי 3 סבבים ותשליטי בירידה. כאב חד בברך, בירך או בגב? עוצרים ובודקים מה קורה.",
    [
      challengeItem("challenge-runner-glutes-bridge", "ex-squat", "גשר ישבן", 3, 12, 45, "12 חזרות עם עצירה של 2 שניות למעלה"),
      challengeItem("challenge-runner-glutes-step", "ex-squat", "עלייה למדרגה", 3, 8, 60, "8 לכל רגל · ברך בקו כף הרגל"),
      challengeItem("challenge-runner-glutes-single", "ex-squat", "סקוואט חד־רגלי נתמך", 3, 6, 60, "6 לכל צד · להחזיק תמיכה"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-strength-foundation",
    "כוח בסיסי פונקציונלי",
    "אימון כוח פשוט ושימושי: דחיפה, רגליים, משיכה וליבה, בלי להגיע לכשל בכל סט.",
    "כוח",
    "מתחילים",
    "6 שבועות",
    "sage",
    "כוח — בסיס לכל הגוף",
    "תשאירי 2–3 חזרות בקופה. עדיף להתאמן קבוע ובאיכות מאשר להעמיס מהר ולהיעלם לשבוע.",
    [
      challengeItem("challenge-strength-foundation-squat", "ex-squat", "סקוואט", 3, 10, 75, "10 חזרות בטווח נוח"),
      challengeItem("challenge-strength-foundation-push", "ex-pushup", "שכיבות סמיכה", 3, 8, 75, "8 חזרות · אפשר שיפוע"),
      challengeItem("challenge-strength-foundation-pull", "ex-pullup", "משיכה / חתירה", 3, 6, 75, "6 חזרות · גומייה או וריאציה מסייעת"),
      challengeItem("challenge-strength-foundation-core", "ex-plank", "פלאנק", 3, 30, 45, "30 שניות"),
    ],
    noSpecialFuel,
  ),
  builtInChallenge(
    "challenge-active-recovery",
    "התאוששות אקטיבית",
    "יום קל של הליכה, מוביליטי ונשימה כדי להחזיר לגוף קצת תנועה בלי להוסיף עומס. גם זה אימון.",
    "מיומנות",
    "מתחילים",
    "3 שבועות",
    "sand",
    "התאוששות — תנועה קלה",
    "תשמרי על קצב שאפשר לדבר בו. אם את גמורה או כואב לך, קחי מנוחה מלאה — זה לא כישלון.",
    [
      challengeItem("challenge-active-recovery-walk", "ex-running", "הליכה קלה", 1, 20, 60, "20 דקות בקצב רגוע"),
      challengeItem("challenge-active-recovery-hips", "ex-squat", "מוביליטי ירכיים", 2, 8, 20, "8 מעברים איטיים לכל צד"),
      challengeItem("challenge-active-recovery-breath", "ex-plank", "נשימה ומתיחה", 2, 60, 20, "דקה של נשימה רגועה ומתיחה עדינה"),
    ],
    noSpecialFuel,
  ),
];

export function cloneChallenge(challenge: Challenge): Challenge {
  const clone: Challenge = {
    ...challenge,
    id: challenge.id,
    sessions: challenge.sessions.map((session) => ({
      ...session,
      items: session.items.map((item) => {
        const copy = { ...item };
        if (item.workingSets) copy.workingSets = item.workingSets.map((set) => ({ ...set }));
        return copy;
      }),
    })),
  };
  if (challenge.nutritionTips) clone.nutritionTips = [...challenge.nutritionTips];
  return clone;
}