import type { Challenge, Workout, WorkoutItem } from "./gym-types";

const challengeItem = (
  id: string,
  exerciseId: string,
  exerciseName: string,
  sets: number,
  reps: number,
  rest: number,
  notes: string,
): WorkoutItem => ({
  id,
  exerciseId,
  exerciseName,
  sets,
  reps,
  repType: "fixed",
  weight: 0,
  rest,
  notes,
  workingSets: Array.from({ length: sets }, (_, index) => ({
    id: `${id}-set-${index + 1}`,
    setNumber: index + 1,
    weight: 0,
    reps,
    rest,
  })),
});

const workout = (id: string, name: string, notes: string, items: WorkoutItem[]): Workout => ({
  id,
  name,
  notes,
  items,
});

const builtInChallenge = (
  id: string,
  title: string,
  description: string,
  category: Challenge["category"],
  difficulty: Challenge["difficulty"],
  durationLabel: string,
  accent: Challenge["accent"],
  sessionName: string,
  sessionNotes: string,
  items: WorkoutItem[],
): Challenge => ({
  id,
  title,
  description,
  category,
  difficulty,
  durationLabel,
  accent,
  isBuiltIn: true,
  isPublished: true,
  sessions: [workout(`${id}-session`, sessionName, sessionNotes, items)],
});

export const BUILT_IN_CHALLENGES: Challenge[] = [
  {
    id: "challenge-20-10",
    title: "אתגר 20/10",
    description: "אימון אינטרוולים קצר וקצבי: 20 שניות עבודה, 10 שניות מנוחה, בלי לרדוף אחרי קצב שפוגע בטכניקה.",
    category: "עצימות",
    difficulty: "מתחילים",
    durationLabel: "8 דקות",
    accent: "peach",
    isBuiltIn: true,
    isPublished: true,
    sessions: [
      workout("challenge-20-10-session", "20/10 — סבב מלא", "8 סבבים. שמור על קצב שאפשר לשלוט בו לאורך כל האימון.", [
        challengeItem("challenge-20-10-mountain", "ex-mountain-climber", "טיפוס הרים", 8, 20, 10, "20 שניות עבודה · 10 שניות מנוחה"),
        challengeItem("challenge-20-10-squat", "ex-squat", "סקוואט", 8, 20, 10, "אפשר לבחור סקוואט משקל גוף"),
        challengeItem("challenge-20-10-pushup", "ex-pushup", "שכיבות סמיכה", 8, 20, 10, "אפשר לעבור לברכיים או לשיפוע"),
      ]),
    ],
  },
  {
    id: "challenge-30-pushups",
    title: "30 שכיבות סמיכה",
    description: "מסלול מדורג לבניית נפח בשכיבות סמיכה. מתקדמים רק כשהטכניקה נשארת נקייה.",
    category: "כוח",
    difficulty: "מתחילים",
    durationLabel: "4 שבועות",
    accent: "sage",
    isBuiltIn: true,
    isPublished: true,
    sessions: [
      workout("challenge-30-pushups-session", "30 שכיבות סמיכה — אימון", "בצע 3–5 סטים. עצור 2 חזרות לפני כשל והשתמש בשיפוע או בברכיים לפי הצורך.", [
        challengeItem("challenge-30-pushups-main", "ex-pushup", "שכיבות סמיכה", 5, 6, 75, "יעד פתיחה: 5×6. כשהכול נקי, הוסף חזרה לסט."),
      ]),
    ],
  },
  {
    id: "challenge-handstand",
    title: "עמידת ידיים",
    description: "בונים שליטה בהדרגה עם עבודה על קו גוף, כתפיים ושהייה על הקיר. לא מתרגלים לבד כשאין סביבת אימון בטוחה.",
    category: "מיומנות",
    difficulty: "מתחילים",
    durationLabel: "3 שבועות",
    accent: "lavender",
    isBuiltIn: true,
    isPublished: true,
    sessions: [
      workout("challenge-handstand-session", "עמידת ידיים — בסיס", "התחל ליד קיר פנוי, עם משטח בטוח, וסיים אם מופיע כאב חד או סחרחורת.", [
        challengeItem("challenge-handstand-plank", "ex-plank", "פלאנק", 3, 30, 45, "30 שניות · בטן וישבן מכווצים"),
        challengeItem("challenge-handstand-ohp", "ex-ohp", "לחיצת כתפיים", 3, 8, 60, "עבודה מבוקרת על כוח כתפיים; אפשר משקל גוף בתרגיל חלופי"),
        challengeItem("challenge-handstand-hold", "ex-plank", "החזקת קו גוף", 5, 20, 45, "20 שניות ליד קיר · איכות לפני זמן"),
      ]),
    ],
  },
  {
    id: "challenge-pullup",
    title: "המתח הראשון",
    description: "מתקדמים מתלייה ושליטה בשכמות לנגטיבים ולמתח מלא. בחר וריאציה שמאפשרת תנועה בשליטה.",
    category: "כוח",
    difficulty: "מתחילים",
    durationLabel: "4 שבועות",
    accent: "sand",
    isBuiltIn: true,
    isPublished: true,
    sessions: [
      workout("challenge-pullup-session", "מתח — בניית בסיס", "הימנע מתנופה. אם אין מתח מלא, עבוד עם גומייה או על שלב נגטיבי.", [
        challengeItem("challenge-pullup-hang", "ex-pullup", "תלייה אקטיבית", 3, 20, 60, "20 שניות · כתפיים רחוקות מהאוזניים"),
        challengeItem("challenge-pullup-scap", "ex-pullup", "משיכת שכמות", 3, 5, 60, "5 חזרות איטיות בטווח קטן"),
        challengeItem("challenge-pullup-negative", "ex-pullup", "נגטיב מתח", 4, 3, 90, "3 חזרות · ירידה של 3–5 שניות"),
      ]),
    ],
  },
  builtInChallenge(
    "challenge-5k-first",
    "5 ק״מ ראשונים",
    "תוכנית ריצה הדרגתית למי שרוצה להגיע ל־5 ק״מ בלי לפתוח מהר מדי. משלבים ריצה והליכה ושומרים על קצב שאפשר לדבר בו.",
    "סבולת",
    "מתחילים",
    "6 שבועות",
    "sage",
    "5 ק״מ — אימון פתיחה",
    "פתחי בקצב קל. המטרה היא לסיים בתחושת יכולת לעוד קצת, לא לנצח את השעון.",
    [
      challengeItem("challenge-5k-first-run", "ex-running", "ריצה / הליכה", 1, 5, 300, "יעד: 5 ק״מ · אפשר לחלק ל־4 דקות ריצה ודקה הליכה"),
    ],
  ),
  builtInChallenge(
    "challenge-10k-builder",
    "בדרך ל־10 ק״מ",
    "אתגר סבולת למי שכבר רצה 5 ק״מ ורוצה לבנות מרחק בביטחון, עם יום התאוששות בין ריצות קשות.",
    "סבולת",
    "ביניים",
    "8 שבועות",
    "lavender",
    "10 ק״מ — ריצה ארוכה",
    "ריצה רציפה בקצב נוח. עצרי אם מופיע כאב חד, והעדיפי יציבות על פני מהירות.",
    [
      challengeItem("challenge-10k-builder-run", "ex-running", "ריצה", 1, 10, 360, "יעד: 10 ק״מ · שמרי את רוב הריצה בקצב קל"),
    ],
  ),
  builtInChallenge(
    "challenge-100-squats",
    "100 סקוואטים",
    "אתגר נפח לרגליים עם חלוקה חכמה לסטים. אין צורך לבצע 100 חזרות ברצף — איכות תנועה קודמת למספר.",
    "כוח",
    "מתחילים",
    "4 שבועות",
    "peach",
    "100 סקוואטים — סבב",
    "בצעי 5 סטים של 20, עם מנוחה לפי הצורך. שמרי על ברכיים בקו האצבעות.",
    [
      challengeItem("challenge-100-squats-main", "ex-squat", "סקוואט", 5, 20, 75, "יעד: 100 חזרות מצטברות · אפשר להתחיל ב־5×10"),
    ],
  ),
  builtInChallenge(
    "challenge-50-lunges",
    "50 לאנג׳ים בשליטה",
    "אתגר חד־צדדי ליציבות, רגליים וישבן. עובדים לאט ומחלקים את החזרות באופן שווה בין הצדדים.",
    "כוח",
    "מתחילים",
    "3 שבועות",
    "sand",
    "50 לאנג׳ים — אימון",
    "ספרי 25 חזרות לכל רגל. החזיקי בקיר אם צריך, ואל תוותרי על יציבות.",
    [
      challengeItem("challenge-50-lunges-main", "ex-squat", "לאנג׳ אחורי", 5, 10, 60, "50 חזרות מצטברות · 5×10 לסירוגין"),
    ],
  ),
  builtInChallenge(
    "challenge-5-minute-plank",
    "5 דקות פלאנק",
    "מסלול לבניית סבולת ליבה דרך מקטעים קצרים. אין חובה להחזיק 5 דקות ברצף.",
    "מיומנות",
    "מתחילים",
    "4 שבועות",
    "sage",
    "5 דקות ליבה — מקטעים",
    "בצעי 5×60 שניות. הורידי ברכיים להפסקה אם הגב מתחיל לשקוע.",
    [
      challengeItem("challenge-5-minute-plank-main", "ex-plank", "פלאנק", 5, 60, 45, "סה״כ 5 דקות · שמרי נשימה וקו גוף"),
    ],
  ),
  builtInChallenge(
    "challenge-100-pushups",
    "100 שכיבות סמיכה",
    "בונים נפח בשכיבות סמיכה עם וריאציה שמתאימה ליכולת. אפשר לעבוד על קיר, שיפוע, ברכיים או רצפה.",
    "כוח",
    "ביניים",
    "6 שבועות",
    "peach",
    "100 שכיבות סמיכה — סבב",
    "חלקי לסטים קטנים והשאירי 1–2 חזרות ברזרבה בכל סט.",
    [
      challengeItem("challenge-100-pushups-main", "ex-pushup", "שכיבות סמיכה", 10, 10, 60, "יעד: 100 חזרות מצטברות · התאימי את הווריאציה"),
    ],
  ),
  builtInChallenge(
    "challenge-10-minute-cardio",
    "10 דקות קרדיו",
    "אימון קצר ועצמתי שאפשר לעשות בבית. עובדים במקטעים ומורידים קצב לפני שהטכניקה נשברת.",
    "עצימות",
    "מתחילים",
    "10 דקות",
    "lavender",
    "10 דקות — אינטרוולים",
    "עשי 10 סבבים של דקה עבודה ודקה בקצב קל. אפשר להחליף ריצה במקום בהליכה מהירה.",
    [
      challengeItem("challenge-10-minute-cardio-run", "ex-running", "ריצה במקום", 10, 60, 30, "10 מקטעים של 60 שניות · קצב בינוני"),
    ],
  ),
  builtInChallenge(
    "challenge-full-body-15",
    "15 דקות גוף מלא",
    "שלושה תרגילים פשוטים שמפעילים רגליים, דחיפה וליבה. מתאים ליום עמוס או לחזרה לשגרה.",
    "עצימות",
    "מתחילים",
    "15 דקות",
    "sage",
    "גוף מלא — 5 סבבים",
    "עברי בין התרגילים בקצב רציף, עם דקה מנוחה בסוף כל סבב.",
    [
      challengeItem("challenge-full-body-15-squat", "ex-squat", "סקוואט", 5, 12, 20, "12 חזרות"),
      challengeItem("challenge-full-body-15-pushup", "ex-pushup", "שכיבות סמיכה", 5, 8, 20, "8 חזרות · אפשר שיפוע"),
      challengeItem("challenge-full-body-15-plank", "ex-plank", "פלאנק", 5, 30, 60, "30 שניות"),
    ],
  ),
  builtInChallenge(
    "challenge-core-trio",
    "ליבת פלדה",
    "רצף ליבה מאוזן שעובד על התנגדות לתנועה, שליטה ונשימה — בלי לרדוף אחרי שריפה בגב.",
    "מיומנות",
    "ביניים",
    "4 שבועות",
    "sand",
    "ליבה — שלושה תרגילים",
    "בצעי 3 סבבים באיכות. אם הגב מתעייף, קצבי את הטווח במקום להוסיף חזרות.",
    [
      challengeItem("challenge-core-trio-plank", "ex-plank", "פלאנק", 3, 45, 30, "45 שניות"),
      challengeItem("challenge-core-trio-climber", "ex-mountain-climber", "מטפס הרים", 3, 20, 30, "20 חזרות לכל צד"),
      challengeItem("challenge-core-trio-dead-bug", "ex-plank", "דד באג", 3, 10, 45, "10 חזרות לכל צד"),
    ],
  ),
  builtInChallenge(
    "challenge-upper-body",
    "פלג גוף עליון בבית",
    "אימון דחיפה ומשיכה שאפשר לבצע עם משקל גוף או עם ציוד זמין. בחרי גרסה שמאפשרת שליטה מלאה.",
    "כוח",
    "ביניים",
    "5 שבועות",
    "lavender",
    "פלג גוף עליון — סבב",
    "בצעי 4 סבבים. מנוחה של 90 שניות בין סבבים ושמרי על כתפיים רגועות.",
    [
      challengeItem("challenge-upper-body-pushup", "ex-pushup", "שכיבות סמיכה", 4, 10, 30, "10 חזרות"),
      challengeItem("challenge-upper-body-pullup", "ex-pullup", "מתח / חתירה", 4, 5, 60, "5 חזרות או וריאציה מסייעת"),
      challengeItem("challenge-upper-body-ohp", "ex-ohp", "לחיצת כתפיים", 4, 8, 45, "8 חזרות בשליטה"),
    ],
  ),
  builtInChallenge(
    "challenge-lower-body",
    "רגליים חזקות",
    "אימון רגליים מדורג עם דגש על שליטה, טווח תנועה והתאוששות. מתאים גם ללא משקולות.",
    "כוח",
    "ביניים",
    "5 שבועות",
    "peach",
    "רגליים — כוח ושליטה",
    "רדי עד לטווח שנשאר יציב. מנוחה של 75–90 שניות בין סטים.",
    [
      challengeItem("challenge-lower-body-squat", "ex-squat", "סקוואט", 4, 10, 75, "10 חזרות"),
      challengeItem("challenge-lower-body-lunge", "ex-squat", "לאנג׳ אחורי", 3, 10, 60, "10 לכל רגל"),
      challengeItem("challenge-lower-body-calf", "ex-squat", "הרמת עקבים", 3, 18, 45, "18 חזרות"),
    ],
  ),
  builtInChallenge(
    "challenge-glute-activation",
    "ישבן פעיל",
    "רצף קצר לישבן ולייצוב האגן. התמקדי בכיווץ ובשליטה, לא במהירות.",
    "כוח",
    "מתחילים",
    "3 שבועות",
    "sand",
    "ישבן — הפעלה",
    "בצעי 3 סבבים עם 45 שניות מנוחה. עצרי אם מופיע כאב בגב התחתון.",
    [
      challengeItem("challenge-glute-activation-bridge", "ex-squat", "גשר ישבן", 3, 15, 30, "15 חזרות עם עצירה למעלה"),
      challengeItem("challenge-glute-activation-squat", "ex-squat", "סקוואט", 3, 12, 45, "12 חזרות"),
      challengeItem("challenge-glute-activation-lunge", "ex-squat", "לאנג׳ אחורי", 3, 8, 45, "8 לכל רגל"),
    ],
  ),
  builtInChallenge(
    "challenge-morning-mobility",
    "10 דקות תנועה בבוקר",
    "רצף עדין לפתיחת הגוף אחרי שינה או ישיבה ממושכת. לא דוחפים מתיחה לתוך כאב.",
    "מיומנות",
    "מתחילים",
    "10 דקות",
    "sage",
    "תנועה בבוקר — זרימה",
    "נשמי עמוק ועברי בין התנועות לאט. זה לא מבחן גמישות.",
    [
      challengeItem("challenge-morning-mobility-plank", "ex-plank", "פלאנק קל", 2, 20, 20, "20 שניות לייצוב"),
      challengeItem("challenge-morning-mobility-squat", "ex-squat", "סקוואט איטי", 2, 8, 20, "8 חזרות בטווח נוח"),
      challengeItem("challenge-morning-mobility-climber", "ex-mountain-climber", "מטפס הרים איטי", 2, 10, 20, "10 לכל צד"),
    ],
  ),
  builtInChallenge(
    "challenge-run-walk-30",
    "30 דקות ריצה־הליכה",
    "אתגר נגיש לבניית הרגל אירובי: שלוש דקות ריצה, שתי דקות הליכה, וחוזרים על הרצף.",
    "סבולת",
    "מתחילים",
    "4 שבועות",
    "peach",
    "ריצה־הליכה — 30 דקות",
    "המטרה היא לסיים את כל חצי השעה בתנועה רציפה, גם אם קצב הריצה איטי.",
    [
      challengeItem("challenge-run-walk-30-main", "ex-running", "ריצה והליכה", 6, 5, 30, "6 סבבים של 3 דקות ריצה ו־2 דקות הליכה"),
    ],
  ),
  builtInChallenge(
    "challenge-10-pullups",
    "10 מתח מצטבר",
    "בונים את הדרך ל־10 חזרות מצטברות בעזרת מתח מלא, גומייה או נגטיבים. כל חזרה איכותית נחשבת.",
    "כוח",
    "מתקדמים",
    "6 שבועות",
    "lavender",
    "10 מתח — נפח",
    "הפסיקי סט לפני תנופה. חלקי את היעד לסטים קטנים ושמרי 2 חזרות ברזרבה.",
    [
      challengeItem("challenge-10-pullups-main", "ex-pullup", "מתח", 5, 2, 90, "יעד: 10 חזרות מצטברות · אפשר גומייה"),
    ],
  ),
  builtInChallenge(
    "challenge-100-mountain-climbers",
    "100 מטפסי הרים",
    "אתגר עצימות קצר לליבה ולדופק. מתחילים לאט מספיק כדי לשמור על אגן יציב לאורך כל הרצף.",
    "עצימות",
    "ביניים",
    "3 שבועות",
    "sand",
    "100 מטפסי הרים — סבבים",
    "בצעי 5×20, עם מנוחה של 45 שניות. אפשר להאט או להניח ידיים על משטח מוגבה.",
    [
      challengeItem("challenge-100-mountain-climbers-main", "ex-mountain-climber", "מטפסי הרים", 5, 20, 45, "100 חזרות מצטברות · 5×20"),
    ],
  ),
];

export function cloneChallenge(challenge: Challenge): Challenge {
  return {
    ...challenge,
    id: challenge.id,
    sessions: challenge.sessions.map((session) => ({
      ...session,
      items: session.items.map((item) => {
        const copy = { ...item };
        if (item.workingSets) copy.workingSets = item.workingSets.map((set) => ({ ...set }));
        return copy;
      }),
    })),
  };
}
