import type { Exercise } from "./gym-types";

type SeedNameMigration = { from: string; to: string };

export const SEED_EXERCISE_NAME_MIGRATIONS: Record<string, SeedNameMigration> = {
  "ex-bench": { from: "לחיצת חזה כנגד מוט", to: "Barbell Bench Press" },
  "ex-squat": { from: "סקואט כנגד מוט (Back Squat)", to: "Barbell Back Squat" },
  "ex-row": { from: "חתירה בכבלים בישיבה", to: "Seated Cable Row" },
  "ex-curl": { from: "כפילת מרפקים עם משקוליות", to: "Dumbbell Biceps Curl" },
  "ex-hipthrust": { from: "דחיקת אגן כנגד מוט (Hip Thrust)", to: "Barbell Hip Thrust" },
  "ex-plank": { from: "פלאנק (Plank)", to: "Front Plank" },
  "ex-ohp": { from: "לחיצת כתפיים בעמידה כנגד מוט", to: "Standing Barbell Overhead Press" },
  "ex-rdl": { from: "דדליפט רומני (RDL)", to: "Romanian Deadlift" },
  "ex-incline-bench": { from: "לחיצת חזה בשיפוע כנגד מוט", to: "Incline Barbell Bench Press" },
  "ex-db-press": { from: "לחיצת חזה כנגד משקוליות", to: "Dumbbell Bench Press" },
  "ex-cable-fly": { from: "קרוס אובר בכבלים", to: "Cable Chest Fly" },
  "ex-chest-press": { from: "לחיצת חזה במכונה", to: "Machine Chest Press" },
  "ex-pullup": { from: "מתח כנגד משקל גוף", to: "Pull-Up" },
  "ex-lat-pulldown": { from: "משיכת פולי עליון", to: "Lat Pulldown" },
  "ex-db-row": { from: "חתירה ביד אחת כנגד משקולית", to: "Single-Arm Dumbbell Row" },
  "ex-face-pull": { from: "משיכת חבל לפנים", to: "Cable Face Pull" },
  "ex-lateral-raise": { from: "הרחקת כתפיים לצדדים", to: "Dumbbell Lateral Raise" },
  "ex-rear-delt-machine": { from: "פשיטת כתף אחורית במכונה", to: "Reverse Pec Deck" },
  "ex-triceps-pushdown": { from: "פשיטת מרפקים בפולי", to: "Cable Triceps Pushdown" },
  "ex-triceps-extension": {
    from: "פשיטת מרפקים מעל הראש",
    to: "Overhead Dumbbell Triceps Extension",
  },
  "ex-leg-press": { from: "לחיצת רגליים במכונה", to: "Leg Press" },
  "ex-leg-extension": { from: "פשיטת ברך במכונה", to: "Leg Extension" },
  "ex-leg-curl": { from: "כפיפת ברך במכונה", to: "Seated Leg Curl" },
  "ex-bulgarian-split": { from: "סקוואט בולגרי", to: "Bulgarian Split Squat" },
  "ex-glute-kickback": { from: "בעיטת ישבן בכבל", to: "Cable Glute Kickback" },
  "ex-calf-raise": { from: "עליות תאומים בעמידה", to: "Standing Calf Raise" },
  "ex-hanging-knee-raise": { from: "הרמת ברכיים בתלייה", to: "Hanging Knee Raise" },
  "ex-dead-bug": { from: "דד באג", to: "Dead Bug" },
  "ex-wrist-curl": { from: "כפיפת שורש כף היד", to: "Dumbbell Wrist Curl" },
  "ex-shrug": { from: "משיכת כתפיים כנגד משקוליות", to: "Dumbbell Shrug" },
  "ex-back-extension": { from: "פשיטת גב על ספסל", to: "Back Extension" },
};

export function renameSeedExercise(exercise: Exercise): Exercise {
  const migration = SEED_EXERCISE_NAME_MIGRATIONS[exercise.id];
  return migration ? { ...exercise, name: migration.to } : exercise;
}

const makeExercise = (
  id: string,
  name: string,
  muscleGroup: string,
  equipment: string,
  description: string,
  _instructions: string,
  category = "מורכב",
): Exercise => ({
  id,
  name,
  muscleGroup,
  muscleGroups: [muscleGroup],
  secondaryMuscles: [],
  category,
  equipment,
  description,
  instructions: "",
  videoUrl: "",
  images: [],
  notes: "",
  tips: "",
});

export const ADDITIONAL_EXERCISES: Exercise[] = [
  makeExercise(
    "ex-cable-pullover",
    "Straight-Arm Cable Pulldown",
    "גב רחב",
    "פולי / כבלים",
    "Pull the cable down in a wide arc while keeping the arms nearly straight.",
    "Brace the ribs, hinge slightly at the hips, and move from the shoulders without swinging.",
    "עזר",
  ),
  makeExercise(
    "ex-chest-supported-row",
    "Chest-Supported Dumbbell Row",
    "גב",
    "משקוליות יד",
    "Row dumbbells from a supported bench position to build the upper back.",
    "Keep the chest on the bench and pull the elbows toward the hips.",
  ),
  makeExercise(
    "ex-tbar-row",
    "T-Bar Row",
    "גב",
    "מוט",
    "Row the bar toward the torso while maintaining a strong neutral back.",
    "Hinge at the hips, keep the spine long, and pause briefly at the top.",
  ),
  makeExercise(
    "ex-incline-db-press",
    "Incline Dumbbell Press",
    "חזה עליון",
    "משקוליות יד",
    "Press dumbbells from an inclined bench to emphasize the upper chest.",
    "Set the shoulder blades, lower with control, and press without locking the elbows hard.",
  ),
  makeExercise(
    "ex-pushup",
    "Push-Up",
    "חזה",
    "משקל גוף",
    "Lower and press the body as one unit from a stable plank position.",
    "Keep the hands under the shoulders and maintain a straight line from head to heels.",
  ),
  makeExercise(
    "ex-dips",
    "Parallel Bar Dips",
    "חזה",
    "משקל גוף",
    "Lower and press the body between parallel bars using the chest and triceps.",
    "Keep the shoulders down and use a comfortable depth without forcing the range.",
  ),
  makeExercise(
    "ex-arnold-press",
    "Arnold Press",
    "כתפיים",
    "משקוליות יד",
    "Rotate dumbbells while pressing overhead through a smooth shoulder movement.",
    "Keep the ribs stacked over the pelvis and control the rotation in both directions.",
  ),
  makeExercise(
    "ex-front-raise",
    "Dumbbell Front Raise",
    "כתף קדמית",
    "משקוליות יד",
    "Raise the dumbbells in front of the body to shoulder height.",
    "Use light weight, soft elbows, and no momentum from the torso.",
    "בידוד",
  ),
  makeExercise(
    "ex-reverse-fly",
    "Dumbbell Reverse Fly",
    "כתף אחורית",
    "משקוליות יד",
    "Open the arms from a hinged position to train the rear deltoids and upper back.",
    "Keep the neck relaxed and lead the movement with the elbows.",
    "בידוד",
  ),
  makeExercise(
    "ex-hammer-curl",
    "Hammer Curl",
    "ביצפס (יד קדמית)",
    "משקוליות יד",
    "Curl dumbbells with a neutral grip to train the biceps and forearms.",
    "Keep the palms facing inward and the elbows close to the ribs.",
    "בידוד",
  ),
  makeExercise(
    "ex-preacher-curl",
    "Preacher Curl",
    "ביצפס (יד קדמית)",
    "מכונה",
    "Curl from a supported arm position with a controlled stretch at the bottom.",
    "Keep the upper arms planted and stop before the elbows lock out.",
    "בידוד",
  ),
  makeExercise(
    "ex-skull-crusher",
    "EZ-Bar Skull Crusher",
    "טריצפס (יד אחורית)",
    "מוט W / EZ",
    "Lower an EZ-bar toward the forehead and extend the elbows to train the triceps.",
    "Keep the upper arms mostly still and use a controlled range of motion.",
    "בידוד",
  ),
  makeExercise(
    "ex-goblet-squat",
    "Goblet Squat",
    "ארבע ראשי",
    "קטלבל",
    "Squat while holding a kettlebell close to the chest.",
    "Keep the chest tall, knees tracking over the toes, and feet grounded.",
  ),
  makeExercise(
    "ex-front-squat",
    "Front Squat",
    "ארבע ראשי",
    "מוט",
    "Squat with the bar in front of the shoulders to challenge the quads and core.",
    "Keep the elbows high and descend with a braced, upright torso.",
  ),
  makeExercise(
    "ex-walking-lunge",
    "Walking Lunge",
    "ישבן",
    "משקל גוף",
    "Step forward into alternating lunges while maintaining balance and control.",
    "Take a long enough step for the front knee to stay aligned with the foot.",
  ),
  makeExercise(
    "ex-step-up",
    "Dumbbell Step-Up",
    "ישבן",
    "משקוליות יד",
    "Step onto a stable platform using one leg at a time.",
    "Drive through the whole foot on the platform and avoid pushing off the trailing leg.",
  ),
  makeExercise(
    "ex-sumo-deadlift",
    "Sumo Deadlift",
    "ישבן",
    "מוט",
    "Lift the bar from a wide stance with the hips and legs working together.",
    "Keep the bar close, brace before lifting, and finish tall without leaning back.",
  ),
  makeExercise(
    "ex-glute-bridge",
    "Glute Bridge",
    "ישבן",
    "משקל גוף",
    "Raise the hips from the floor while squeezing the glutes at the top.",
    "Keep the ribs down and avoid arching the lower back.",
    "בידוד",
  ),
  makeExercise(
    "ex-seated-calf",
    "Seated Calf Raise",
    "תאומים",
    "מכונה",
    "Lift and lower the heels from a seated position to train the calf muscles.",
    "Use a full comfortable range and pause at the top.",
    "בידוד",
  ),
  makeExercise(
    "ex-cable-woodchop",
    "Cable Wood Chop",
    "אלכסונים",
    "פולי / כבלים",
    "Rotate the cable diagonally across the body with control.",
    "Move through the torso while keeping the hips stable and the spine long.",
    "עזר",
  ),
  makeExercise(
    "ex-side-plank",
    "Side Plank",
    "אלכסונים",
    "משקל גוף",
    "Hold a straight side-facing position using the obliques and lateral core.",
    "Stack the shoulders and hips, and keep the body in one long line.",
    "בידוד",
  ),
  makeExercise(
    "ex-bird-dog",
    "Bird Dog",
    "בטן",
    "משקל גוף",
    "Extend the opposite arm and leg from an all-fours position.",
    "Keep the hips level and move slowly without rotating the torso.",
    "בידוד",
  ),
  makeExercise(
    "ex-mountain-climber",
    "Mountain Climber",
    "אירובי",
    "משקל גוף",
    "Alternate driving the knees toward the chest from a strong plank.",
    "Keep the shoulders over the hands and choose a pace that preserves alignment.",
    "אירובי",
  ),
  makeExercise(
    "ex-kettlebell-swing",
    "Kettlebell Swing",
    "גוף מלא",
    "קטלבל",
    "Use a powerful hip hinge to swing the kettlebell to chest height.",
    "Snap the hips forward, keep the arms relaxed, and do not squat the swing.",
  ),
  makeExercise(
    "ex-battle-rope",
    "Battle Rope Waves",
    "גוף מלא",
    "אחר",
    "Create alternating rope waves while maintaining a stable athletic stance.",
    "Brace the core, keep the shoulders relaxed, and work at a repeatable pace.",
    "אירובי",
  ),
  makeExercise(
    "ex-jumping-jack",
    "Jumping Jack",
    "אירובי",
    "משקל גוף",
    "Jump while opening and closing the arms and legs in a steady rhythm.",
    "Land softly with knees slightly bent and select a low-impact version when needed.",
    "אירובי",
  ),
  makeExercise(
    "ex-hip-flexor-stretch",
    "Half-Kneeling Hip Flexor Stretch",
    "כופפי הירך",
    "משקל גוף",
    "Stretch the front of the hip from a half-kneeling position.",
    "Tuck the pelvis gently and shift forward without arching the lower back.",
    "גמישות / ניעות",
  ),
  makeExercise(
    "ex-worlds-greatest-stretch",
    "World's Greatest Stretch",
    "גוף מלא",
    "משקל גוף",
    "Flow through a lunge, rotation, and hamstring stretch to improve mobility.",
    "Move slowly, breathe continuously, and stay within a comfortable range.",
    "גמישות / ניעות",
  ),
];
