import type {
  FoodCatalogMetadata,
  FoodItem,
  FoodCatalogProductType,
} from "./gym-types";

type CuratedProduct = Omit<FoodItem, "catalog"> & {
  catalog: FoodCatalogMetadata;
};

const DANONE_PRO_STRAWBERRY_SOURCE =
  "https://danone.strauss-group.com/products/%D7%99%D7%95%D7%92%D7%95%D7%A8%D7%98-%D7%91%D7%98%D7%A2%D7%9D-%D7%AA%D7%95%D7%AA-20-%D7%92%D7%A8%D7%9D-%D7%97%D7%9C%D7%91%D7%95%D7%9F-0-%D7%A9%D7%95%D7%9E%D7%9F-2/";

const curatedProduct = (
  id: string,
  name: string,
  brand: string,
  productType: FoodCatalogProductType,
  category: string,
  servingSize: string,
  packageSize: string,
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
  sourceUrl: string,
  searchTerms: string[] = [],
  nutritionReview?: FoodItem["nutritionReview"],
  fiber = 0,
): CuratedProduct => {
  const resolvedSourceUrl = id === "f-protein-il-danone-pro-strawberry"
    ? DANONE_PRO_STRAWBERRY_SOURCE
    : sourceUrl;
  const resolvedNutritionReview = nutritionReview
    ? {
        ...nutritionReview,
        sources: nutritionReview.sources.map((source) =>
          source.name.startsWith("דנונה שטראוס")
            ? { ...source, url: DANONE_PRO_STRAWBERRY_SOURCE }
            : source,
        ),
      }
    : undefined;

  return {
    id,
    name,
    englishName: `${brand} protein`,
    category,
    brand,
    servingSize,
    calories,
    protein,
    carbs,
    fat,
    fiber,
    searchTerms: [...searchTerms, brand, "חלבון", "protein"],
    notes:
      "ערך seed לקטלוג מוצרי חלבון בישראל. יש לבדוק את התווית שעל האריזה לפני שימוש מדויק.",
    catalog: {
      source: "curated-israel",
      sourceProductId: id,
      sourceUrl: resolvedSourceUrl,
      productType,
      market: "IL",
      packageSize,
      verificationStatus: "curated-unverified",
    },
    ...(resolvedNutritionReview ? { nutritionReview: resolvedNutritionReview } : {}),
  };
};

/**
 * A small, offline-safe layer for recognizable Israeli supermarket protein
 * products. It intentionally does not invent barcodes: imported barcodes are
 * added only when the external source provides one.
 */
export const ISRAELI_PROTEIN_PRODUCTS: FoodItem[] = [
  curatedProduct(
    "f-protein-il-tnuva-go-yogurt-natural",
    "יופלה GO יוגורט חלבון טבעי 20g",
    "יופלה GO",
    "yogurt",
    "יוגורטי חלבון",
    "גביע (200 גרם)",
    "200 גרם",
    144,
    20,
    7,
    4,
    "https://www.tnuva.co.il/products/%D7%99%D7%95%D7%A4%D7%9C%D7%94-%D7%92%D7%95-%D7%99%D7%95%D7%92%D7%95%D7%A8%D7%98-%D7%9E%D7%95%D7%A2%D7%A9%D7%A8-%D7%91%D7%97%D7%9C%D7%91%D7%95%D7%9F-%D7%98%D7%91%D7%A2%D7%99/",
    ["יוגורט", "פרו", "טבעי"],
    {
      status: "reviewed",
      checkedAt: "2026-08-31",
      confidence: "high",
      method: "official",
      sources: [
        {
          name: "תנובה — יופלה GO טבעי 20g",
          url: "https://www.tnuva.co.il/products/%D7%99%D7%95%D7%A4%D7%9C%D7%94-%D7%92%D7%95-%D7%99%D7%95%D7%92%D7%95%D7%A8%D7%98-%D7%9E%D7%95%D7%A2%D7%A9%D7%A8-%D7%91%D7%97%D7%9C%D7%91%D7%95%D7%9F-%D7%98%D7%91%D7%A2%D7%99/",
          kind: "manufacturer",
          match: "exact-product",
          valuesPer: "100g",
        },
      ],
      notes: "ערכי המנה חושבו מטבלת היצרן ל־100 גרם עבור גביע של 200 גרם.",
    },
  ),
  curatedProduct(
    "f-protein-il-danone-pro-strawberry",
    "דנונה PRO יוגורט חלבון תות 20g",
    "דנונה PRO",
    "yogurt",
    "יוגורטי חלבון",
    "גביע (200 גרם)",
    "200 גרם",
    130,
    20,
    11.2,
    0,
    "https://danone.strauss-group.com/products/%D7%99%D7%95%D7%92%D7%95%D7%A8%D7%98-%D7%91%D7%98%D7%A2%D7%9D-%D7%AA%D7%ות-20-%D7%92%D7%A8%D7%B3-%D7%97%D7%9C%D7%91%D7%95%D7%9F-0-%D7%A9%D7%95%D7%9E%D7%9F-2/",
    ["דנונה", "יוגורט", "תות"],
    {
      status: "reviewed",
      checkedAt: "2026-08-31",
      confidence: "high",
      method: "official",
      sources: [
        {
          name: "דנונה שטראוס — PRO תות 20g",
          url: "https://danone.strauss-group.com/products/%D7%99%D7%95%D7%92%D7%95%D7%A8%D7%98-%D7%91%D7%98%D7%A2%D7%9D-%D7%AA%D7%ות-20-%D7%92%D7%A8%D7%9D-%D7%97%D7%9C%D7%91%D7%95%D7%9F-0-%D7%A9%D7%95%D7%9E%D7%9F-2/",
          kind: "manufacturer",
          match: "exact-product",
          valuesPer: "100g",
        },
      ],
      notes: "ערכי המנה חושבו מטבלת היצרן ל־100 גרם עבור גביע של 200 גרם.",
    },
  ),
  curatedProduct(
    "f-protein-il-yoplait-pro-natural",
    "יופלה PRO יוגורט חלבון טבעי 15g",
    "יופלה PRO",
    "yogurt",
    "יוגורטי חלבון",
    "גביע (150 גרם)",
    "150 גרם",
    110,
    15,
    11,
    0.3,
    "https://www.tnuva.co.il/",
    ["יופלה", "יוגורט", "סקיר"],
  ),
  curatedProduct(
    "f-protein-il-go-pudding-chocolate",
    "מעדן GO חלבון שוקולד 20g",
    "GO",
    "pudding",
    "מעדני חלבון",
    "גביע (200 גרם)",
    "200 גרם",
    156,
    20,
    14,
    2,
    "https://www.tnuva.co.il/",
    ["מעדן", "שוקולד", "תנובה"],
  ),
  curatedProduct(
    "f-protein-il-go-pudding-vanilla",
    "מעדן GO חלבון וניל 20g",
    "GO",
    "pudding",
    "מעדני חלבון",
    "גביע (200 גרם)",
    "200 גרם",
    150,
    20,
    13,
    1.8,
    "https://www.tnuva.co.il/",
    ["מעדן", "וניל", "תנובה"],
  ),
  curatedProduct(
    "f-protein-il-yotvata-pro-chocolate",
    "יטבתה PRO משקה חלבון שוקו 25g",
    "יטבתה PRO",
    "drink",
    "משקאות חלבון",
    "בקבוק (330 מ״ל)",
    "330 מ״ל",
    180,
    25,
    13,
    3,
    "https://www.yotvata.co.il/",
    ["שוקו", "משקה", "יוטבתה"],
  ),
  curatedProduct(
    "f-protein-il-tnuva-go-drink-vanilla",
    "תנובה GO משקה חלבון וניל 25g",
    "תנובה GO",
    "drink",
    "משקאות חלבון",
    "בקבוק (330 מ״ל)",
    "330 מ״ל",
    160,
    25,
    10,
    2,
    "https://www.tnuva.co.il/",
    ["משקה", "שייק", "וניל"],
  ),
  curatedProduct(
    "f-protein-il-tera-pro-drink",
    "טרה PRO משקה חלבון 25g",
    "טרה PRO",
    "drink",
    "משקאות חלבון",
    "בקבוק (330 מ״ל)",
    "330 מ״ל",
    170,
    25,
    12,
    2,
    "https://www.terra.co.il/",
    ["משקה", "טרה"],
  ),
  curatedProduct(
    "f-protein-il-tnuva-cottage-pro",
    "תנובה קוטג׳ PRO 12g חלבון",
    "תנובה",
    "other",
    "מוצרי חלבון",
    "100 גרם",
    "250 גרם",
    98,
    12,
    3,
    5,
    "https://www.tnuva.co.il/",
    ["קוטג׳", "גבינה", "קוטג"],
  ),
  curatedProduct(
    "f-protein-il-allin-bar-chocolate",
    "Allin Extra Soft חטיף חלבון שוקולד חלב קרמל",
    "Allin",
    "bar",
    "חטיפי חלבון",
    "חטיף (55 גרם)",
    "מארז 18 × 55 גרם",
    203,
    15,
    20.6,
    9.1,
    "https://www.allinpro.co.il/products/khtyp-khlbvn-bt-m-shvqvld-khlb-qrml",
    ["חטיף", "שוקולד", "קרמל"],
    {
      status: "reviewed",
      checkedAt: "2026-08-31",
      confidence: "high",
      method: "official",
      sources: [
        {
          name: "Allin — Extra Soft שוקולד חלב קרמל",
          url: "https://www.allinpro.co.il/products/khtyp-khlbvn-bt-m-shvqvld-khlb-qrml",
          kind: "manufacturer",
          match: "exact-product",
          valuesPer: "serving",
        },
      ],
      notes: "ערכי המנה נלקחו מטבלת היצרן עבור חטיף של 55 גרם; סיבים: 3.6 גרם.",
    },
    3.6,
  ),
  curatedProduct(
    "f-protein-il-max-bar",
    "MAX חטיף חלבון",
    "MAX",
    "bar",
    "חטיפי חלבון",
    "חטיף (55 גרם)",
    "55 גרם",
    200,
    20,
    17,
    7,
    "https://www.maxsport.co.il/",
    ["חטיף", "מקס"],
  ),
  curatedProduct(
    "f-protein-il-israelbody-whey",
    "Israel Body אבקת חלבון מי גבינה",
    "Israel Body",
    "powder",
    "אבקות חלבון",
    "מנה (30 גרם)",
    "1 ק״ג",
    120,
    24,
    3,
    2,
    "https://www.israelbody.org/",
    ["אבקה", "whey", "מי גבינה"],
  ),
  curatedProduct(
    "f-protein-il-allin-whey-vanilla",
    "Allin Whey אבקת חלבון וניל",
    "Allin",
    "powder",
    "אבקות חלבון",
    "מנה (33 גרם)",
    "2.013 ק״ג",
    128,
    25,
    3.1,
    1.5,
    "https://www.israelbody.org/products/allin-wpc-isr",
    ["אבקה", "whey", "וניל"],
    {
      status: "reviewed",
      checkedAt: "2026-08-31",
      confidence: "medium",
      method: "retailer-product-page",
      sources: [
        {
          name: "Israel Body — Allin Whey וניל",
          url: "https://www.israelbody.org/products/allin-wpc-isr",
          kind: "retailer-product-page",
          match: "exact-product",
          valuesPer: "serving",
        },
      ],
      notes: "טבלת המוצר מציינת מנה של 33 גרם: 128 קלוריות, 25g חלבון, 3.1g פחמימות ו־1.5g שומן. יש להעדיף את תווית האריזה אם היא שונה.",
    },
  ),
  curatedProduct(
    "f-protein-il-superherb-protein-powder",
    "סופהרב אבקת חלבון",
    "סופהרב",
    "powder",
    "אבקות חלבון",
    "מנה (30 גרם)",
    "750 גרם",
    115,
    23,
    3,
    1.5,
    "https://www.supherb.co.il/",
    ["אבקה", "מי גבינה", "סופרב"],
  ),
];
