import type {
  FoodCatalogMetadata,
  FoodItem,
  FoodCatalogProductType,
} from "./gym-types";

type CuratedProduct = Omit<FoodItem, "catalog"> & {
  catalog: FoodCatalogMetadata;
};

const curatedProduct = (
  id: string,
  name: string,
  brand: string,
  productType: FoodCatalogProductType,
  category: string,
  servingSize: string,
  packageSize: string,
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
  sourceUrl: string,
  searchTerms: string[] = [],
): CuratedProduct => ({
  id,
  name,
  englishName: `${brand} protein`,
  category,
  brand,
  servingSize,
  calories,
  protein,
  carbs,
  fat,
  fiber: 0,
  searchTerms: [...searchTerms, brand, "חלבון", "protein"],
  notes:
    "ערך seed לקטלוג מוצרי חלבון בישראל. יש לבדוק את התווית שעל האריזה לפני שימוש מדויק.",
  catalog: {
    source: "curated-israel",
    sourceProductId: id,
    sourceUrl,
    productType,
    market: "IL",
    packageSize,
    verificationStatus: "curated-unverified",
  },
});

/**
 * A small, offline-safe layer for recognizable Israeli supermarket protein
 * products. It intentionally does not invent barcodes: imported barcodes are
 * added only when the external source provides one.
 */
export const ISRAELI_PROTEIN_PRODUCTS: FoodItem[] = [
  curatedProduct(
    "f-protein-il-tnuva-go-yogurt-natural",
    "תנובה GO יוגורט חלבון טבעי 20g",
    "תנובה GO",
    "yogurt",
    "יוגורטי חלבון",
    "גביע (200 גרם)",
    "200 גרם",
    120,
    20,
    9,
    0.4,
    "https://www.tnuva.co.il/",
    ["יוגורט", "פרו", "טבעי"],
  ),
  curatedProduct(
    "f-protein-il-danone-pro-strawberry",
    "דנונה PRO יוגורט חלבון תות 20g",
    "דנונה PRO",
    "yogurt",
    "יוגורטי חלבון",
    "גביע (200 גרם)",
    "200 גרם",
    150,
    20,
    16,
    0.4,
    "https://www.danone.co.il/",
    ["דנונה", "יוגורט", "תות"],
  ),
  curatedProduct(
    "f-protein-il-yoplait-pro-natural",
    "יופלה PRO יוגורט חלבון טבעי 15g",
    "יופלה PRO",
    "yogurt",
    "יוגורטי חלבון",
    "גביע (150 גרם)",
    "150 גרם",
    110,
    15,
    11,
    0.3,
    "https://www.tnuva.co.il/",
    ["יופלה", "יוגורט", "סקיר"],
  ),
  curatedProduct(
    "f-protein-il-go-pudding-chocolate",
    "מעדן GO חלבון שוקולד 20g",
    "GO",
    "pudding",
    "מעדני חלבון",
    "גביע (200 גרם)",
    "200 גרם",
    156,
    20,
    14,
    2,
    "https://www.tnuva.co.il/",
    ["מעדן", "שוקולד", "תנובה"],
  ),
  curatedProduct(
    "f-protein-il-go-pudding-vanilla",
    "מעדן GO חלבון וניל 20g",
    "GO",
    "pudding",
    "מעדני חלבון",
    "גביע (200 גרם)",
    "200 גרם",
    150,
    20,
    13,
    1.8,
    "https://www.tnuva.co.il/",
    ["מעדן", "וניל", "תנובה"],
  ),
  curatedProduct(
    "f-protein-il-yotvata-pro-chocolate",
    "יטבתה PRO משקה חלבון שוקו 25g",
    "יטבתה PRO",
    "drink",
    "משקאות חלבון",
    "בקבוק (330 מ״ל)",
    "330 מ״ל",
    180,
    25,
    13,
    3,
    "https://www.yotvata.co.il/",
    ["שוקו", "משקה", "יוטבתה"],
  ),
  curatedProduct(
    "f-protein-il-tnuva-go-drink-vanilla",
    "תנובה GO משקה חלבון וניל 25g",
    "תנובה GO",
    "drink",
    "משקאות חלבון",
    "בקבוק (330 מ״ל)",
    "330 מ״ל",
    160,
    25,
    10,
    2,
    "https://www.tnuva.co.il/",
    ["משקה", "שייק", "וניל"],
  ),
  curatedProduct(
    "f-protein-il-tera-pro-drink",
    "טרה PRO משקה חלבון 25g",
    "טרה PRO",
    "drink",
    "משקאות חלבון",
    "בקבוק (330 מ״ל)",
    "330 מ״ל",
    170,
    25,
    12,
    2,
    "https://www.terra.co.il/",
    ["משקה", "טרה"],
  ),
  curatedProduct(
    "f-protein-il-tnuva-cottage-pro",
    "תנובה קוטג׳ PRO 12g חלבון",
    "תנובה",
    "other",
    "מוצרי חלבון",
    "100 גרם",
    "250 גרם",
    98,
    12,
    3,
    5,
    "https://www.tnuva.co.il/",
    ["קוטג׳", "גבינה", "קוטג"],
  ),
  curatedProduct(
    "f-protein-il-allin-bar-chocolate",
    "Allin חטיף חלבון שוקולד",
    "Allin",
    "bar",
    "חטיפי חלבון",
    "חטיף (60 גרם)",
    "60 גרם",
    210,
    20,
    18,
    8,
    "https://www.allin.co.il/",
    ["חטיף", "שוקולד"],
  ),
  curatedProduct(
    "f-protein-il-max-bar",
    "MAX חטיף חלבון",
    "MAX",
    "bar",
    "חטיפי חלבון",
    "חטיף (55 גרם)",
    "55 גרם",
    200,
    20,
    17,
    7,
    "https://www.maxsport.co.il/",
    ["חטיף", "מקס"],
  ),
  curatedProduct(
    "f-protein-il-israelbody-whey",
    "Israel Body אבקת חלבון מי גבינה",
    "Israel Body",
    "powder",
    "אבקות חלבון",
    "מנה (30 גרם)",
    "1 ק״ג",
    120,
    24,
    3,
    2,
    "https://www.israelbody.org/",
    ["אבקה", "whey", "מי גבינה"],
  ),
  curatedProduct(
    "f-protein-il-allin-whey-vanilla",
    "Allin Whey אבקת חלבון וניל",
    "Allin",
    "powder",
    "אבקות חלבון",
    "מנה (30 גרם)",
    "900 גרם",
    120,
    24,
    3,
    2,
    "https://www.allin.co.il/",
    ["אבקה", "whey", "וניל"],
  ),
  curatedProduct(
    "f-protein-il-superherb-protein-powder",
    "סופהרב אבקת חלבון",
    "סופהרב",
    "powder",
    "אבקות חלבון",
    "מנה (30 גרם)",
    "750 גרם",
    115,
    23,
    3,
    1.5,
    "https://www.supherb.co.il/",
    ["אבקה", "מי גבינה", "סופרב"],
  ),
];
