/**
 * USDA FoodData Central reference expansion — 303 items.
 * IDs are prefixed "f-usda-" so the sync layer treats them as seeds.
 * Values are per-serving seed estimates; every row carries an unreviewed
 * FoodData Central reference rather than claiming exact-product verification.
 */
import type { FoodItem } from "./gym-types";

const USDA_FOOD_EXPANSION_SEED: FoodItem[] = [
  // ── דגני בוקר ─────────────────────────────────────────────────────────────
  {
    id: "f-usda-cereal-001",
    name: "קורנפלקס",
    englishName: "Corn Flakes",
    category: "דגני בוקר",
    servingSize: "30 גרם",
    calories: 114,
    protein: 2,
    carbs: 25,
    fat: 0,
    fiber: 0.6,
  },
  {
    id: "f-usda-cereal-002",
    name: "צ׳יריוס",
    englishName: "Cheerios",
    category: "דגני בוקר",
    servingSize: "30 גרם",
    calories: 111,
    protein: 3,
    carbs: 22,
    fat: 2,
    fiber: 3,
  },
  {
    id: "f-usda-cereal-003",
    name: "גרנולה אגוזים",
    englishName: "Granola with nuts",
    category: "דגני בוקר",
    servingSize: "45 גרם",
    calories: 208,
    protein: 5,
    carbs: 30,
    fat: 8,
    fiber: 3,
  },
  {
    id: "f-usda-cereal-004",
    name: "מוסלי",
    englishName: "Muesli",
    category: "דגני בוקר",
    servingSize: "45 גרם",
    calories: 168,
    protein: 5,
    carbs: 31,
    fat: 3,
    fiber: 3,
  },
  {
    id: "f-usda-cereal-005",
    name: "שיבולת שועל מיידית",
    englishName: "Instant Oatmeal",
    category: "דגני בוקר",
    servingSize: "40 גרם",
    calories: 150,
    protein: 4,
    carbs: 27,
    fat: 3,
    fiber: 2,
  },
  {
    id: "f-usda-cereal-006",
    name: "ריים קריספיז",
    englishName: "Rice Krispies",
    category: "דגני בוקר",
    servingSize: "30 גרם",
    calories: 108,
    protein: 2,
    carbs: 24,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-cereal-007",
    name: "ספציאל קיי",
    englishName: "Special K",
    category: "דגני בוקר",
    servingSize: "30 גרם",
    calories: 117,
    protein: 7,
    carbs: 22,
    fat: 1,
    fiber: 1,
  },
  {
    id: "f-usda-cereal-008",
    name: "חמולין",
    englishName: "Raisin Bran",
    category: "דגני בוקר",
    servingSize: "55 גרם",
    calories: 190,
    protein: 5,
    carbs: 46,
    fat: 2,
    fiber: 7,
  },
  {
    id: "f-usda-cereal-009",
    name: "וויטביקס",
    englishName: "Weetabix",
    category: "דגני בוקר",
    servingSize: "38 גרם (2 עוגיות)",
    calories: 136,
    protein: 5,
    carbs: 26,
    fat: 1,
    fiber: 4,
  },
  {
    id: "f-usda-cereal-010",
    name: "פרי לופס",
    englishName: "Froot Loops",
    category: "דגני בוקר",
    servingSize: "29 גרם",
    calories: 111,
    protein: 1,
    carbs: 25,
    fat: 1,
    fiber: 1,
  },
  {
    id: "f-usda-cereal-011",
    name: "קפטן קראנץ׳",
    englishName: "Cap'n Crunch",
    category: "דגני בוקר",
    servingSize: "27 גרם",
    calories: 108,
    protein: 2,
    carbs: 23,
    fat: 1,
    fiber: 1,
  },
  {
    id: "f-usda-cereal-012",
    name: "פרוסטד מיניוויטס",
    englishName: "Frosted Mini Wheats",
    category: "דגני בוקר",
    servingSize: "59 גרם",
    calories: 200,
    protein: 6,
    carbs: 48,
    fat: 1,
    fiber: 6,
  },
  {
    id: "f-usda-cereal-013",
    name: "גרנולה שוקולד",
    englishName: "Chocolate Granola",
    category: "דגני בוקר",
    servingSize: "45 גרם",
    calories: 196,
    protein: 4,
    carbs: 30,
    fat: 7,
    fiber: 3,
  },
  {
    id: "f-usda-cereal-014",
    name: "שיבולת שועל פלדה",
    englishName: "Steel Cut Oats",
    category: "דגני בוקר",
    servingSize: "40 גרם יבש",
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
    fiber: 3,
  },
  {
    id: "f-usda-cereal-015",
    name: "הני סמאקס",
    englishName: "Honey Smacks",
    category: "דגני בוקר",
    servingSize: "27 גרם",
    calories: 100,
    protein: 2,
    carbs: 24,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-cereal-016",
    name: "קוקו פאפס",
    englishName: "Cocoa Puffs",
    category: "דגני בוקר",
    servingSize: "30 גרם",
    calories: 117,
    protein: 1,
    carbs: 26,
    fat: 1,
    fiber: 1,
  },
  {
    id: "f-usda-cereal-017",
    name: "הני קראנץ׳ אוט",
    englishName: "Honey Bunches of Oats",
    category: "דגני בוקר",
    servingSize: "30 גרם",
    calories: 120,
    protein: 2,
    carbs: 25,
    fat: 2,
    fiber: 1,
  },
  {
    id: "f-usda-cereal-018",
    name: "פרוסטד פלייקס",
    englishName: "Frosted Flakes",
    category: "דגני בוקר",
    servingSize: "30 גרם",
    calories: 114,
    protein: 1,
    carbs: 27,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-cereal-019",
    name: "פייבר ואן",
    englishName: "Fiber One Original",
    category: "דגני בוקר",
    servingSize: "30 גרם",
    calories: 60,
    protein: 2,
    carbs: 25,
    fat: 1,
    fiber: 14,
  },
  {
    id: "f-usda-cereal-020",
    name: "לוקי צ׳ארמס",
    englishName: "Lucky Charms",
    category: "דגני בוקר",
    servingSize: "30 גרם",
    calories: 116,
    protein: 2,
    carbs: 25,
    fat: 1,
    fiber: 1,
  },

  // ── לחמים ומאפים ───────────────────────────────────────────────────────────
  {
    id: "f-usda-bread-001",
    name: "לחם לבן",
    englishName: "White Bread",
    category: "לחמים",
    servingSize: "פרוסה (30 גרם)",
    calories: 79,
    protein: 3,
    carbs: 15,
    fat: 1,
    fiber: 1,
  },
  {
    id: "f-usda-bread-002",
    name: "לחם שיפון",
    englishName: "Rye Bread",
    category: "לחמים",
    servingSize: "פרוסה (32 גרם)",
    calories: 83,
    protein: 3,
    carbs: 15,
    fat: 1,
    fiber: 2,
  },
  {
    id: "f-usda-bread-003",
    name: "בייגל",
    englishName: "Bagel",
    category: "לחמים",
    servingSize: "בייגל (98 גרם)",
    calories: 270,
    protein: 10,
    carbs: 53,
    fat: 2,
    fiber: 2,
  },
  {
    id: "f-usda-bread-004",
    name: "בייגל שלם",
    englishName: "Whole Wheat Bagel",
    category: "לחמים",
    servingSize: "בייגל (98 גרם)",
    calories: 260,
    protein: 11,
    carbs: 51,
    fat: 2,
    fiber: 4,
  },
  {
    id: "f-usda-bread-005",
    name: "קרקר מלח",
    englishName: "Saltine Crackers",
    category: "לחמים",
    servingSize: "5 קרקרים (15 גרם)",
    calories: 65,
    protein: 1,
    carbs: 11,
    fat: 2,
    fiber: 0,
  },
  {
    id: "f-usda-bread-006",
    name: "קרקר מלא",
    englishName: "Whole Wheat Crackers",
    category: "לחמים",
    servingSize: "5 קרקרים (16 גרם)",
    calories: 70,
    protein: 2,
    carbs: 11,
    fat: 2,
    fiber: 1,
  },
  {
    id: "f-usda-bread-007",
    name: "פיתה לבנה",
    englishName: "Pita Bread White",
    category: "לחמים",
    servingSize: "פיתה (60 גרם)",
    calories: 165,
    protein: 5,
    carbs: 33,
    fat: 1,
    fiber: 1,
  },
  {
    id: "f-usda-bread-008",
    name: "לחמנייה המבורגר",
    englishName: "Hamburger Bun",
    category: "לחמים",
    servingSize: "לחמנייה (43 גרם)",
    calories: 120,
    protein: 4,
    carbs: 22,
    fat: 2,
    fiber: 1,
  },
  {
    id: "f-usda-bread-009",
    name: "קרואסון",
    englishName: "Croissant",
    category: "לחמים",
    servingSize: "קרואסון (57 גרם)",
    calories: 231,
    protein: 5,
    carbs: 26,
    fat: 12,
    fiber: 1,
  },
  {
    id: "f-usda-bread-010",
    name: "מאפין אנגלי",
    englishName: "English Muffin",
    category: "לחמים",
    servingSize: "מאפין (57 גרם)",
    calories: 134,
    protein: 5,
    carbs: 26,
    fat: 1,
    fiber: 2,
  },
  {
    id: "f-usda-bread-011",
    name: "פוקצ׳ה",
    englishName: "Focaccia",
    category: "לחמים",
    servingSize: "100 גרם",
    calories: 249,
    protein: 7,
    carbs: 38,
    fat: 9,
    fiber: 2,
  },
  {
    id: "f-usda-bread-012",
    name: "לחם שאור",
    englishName: "Sourdough Bread",
    category: "לחמים",
    servingSize: "פרוסה (35 גרם)",
    calories: 89,
    protein: 4,
    carbs: 17,
    fat: 1,
    fiber: 1,
  },
  {
    id: "f-usda-bread-013",
    name: "נאן",
    englishName: "Naan Bread",
    category: "לחמים",
    servingSize: "נאן (90 גרם)",
    calories: 262,
    protein: 9,
    carbs: 45,
    fat: 5,
    fiber: 2,
  },
  {
    id: "f-usda-bread-014",
    name: "טורטייה קמח",
    englishName: "Flour Tortilla",
    category: "לחמים",
    servingSize: "טורטייה גדולה (45 גרם)",
    calories: 146,
    protein: 4,
    carbs: 25,
    fat: 4,
    fiber: 2,
  },
  {
    id: "f-usda-bread-015",
    name: "טורטייה תירס",
    englishName: "Corn Tortilla",
    category: "לחמים",
    servingSize: "2 טורטיות (46 גרם)",
    calories: 103,
    protein: 3,
    carbs: 21,
    fat: 1,
    fiber: 3,
  },

  // ── בשר ועוף ───────────────────────────────────────────────────────────────
  {
    id: "f-usda-meat-001",
    name: "חזה הודו מבושל",
    englishName: "Turkey Breast Cooked",
    category: "עוף ועופות",
    servingSize: "85 גרם",
    calories: 135,
    protein: 26,
    carbs: 0,
    fat: 3,
    fiber: 0,
  },
  {
    id: "f-usda-meat-002",
    name: "פרגית עוף מבושלת",
    englishName: "Chicken Thigh Cooked",
    category: "עוף ועופות",
    servingSize: "85 גרם",
    calories: 178,
    protein: 22,
    carbs: 0,
    fat: 9,
    fiber: 0,
  },
  {
    id: "f-usda-meat-003",
    name: "כנפי עוף",
    englishName: "Chicken Wings",
    category: "עוף ועופות",
    servingSize: "4 כנפיים (85 גרם)",
    calories: 203,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  {
    id: "f-usda-meat-004",
    name: "חזה הודו פרוס",
    englishName: "Sliced Turkey Breast",
    category: "עוף ועופות",
    servingSize: "2 פרוסות (56 גרם)",
    calories: 60,
    protein: 11,
    carbs: 1,
    fat: 1,
    fiber: 0,
  },
  {
    id: "f-usda-meat-005",
    name: "קבב הודו",
    englishName: "Turkey Kebab",
    category: "עוף ועופות",
    servingSize: "100 גרם",
    calories: 185,
    protein: 24,
    carbs: 2,
    fat: 9,
    fiber: 0,
  },
  {
    id: "f-usda-meat-006",
    name: "ביף סטייק סינטה",
    englishName: "Beef Sirloin Steak",
    category: "בקר וכבש",
    servingSize: "100 גרם",
    calories: 207,
    protein: 29,
    carbs: 0,
    fat: 10,
    fiber: 0,
  },
  {
    id: "f-usda-meat-007",
    name: "בשר טחון 80/20",
    englishName: "Ground Beef 80/20",
    category: "בקר וכבש",
    servingSize: "100 גרם",
    calories: 254,
    protein: 17,
    carbs: 0,
    fat: 20,
    fiber: 0,
  },
  {
    id: "f-usda-meat-008",
    name: "ריביי",
    englishName: "Ribeye Steak",
    category: "בקר וכבש",
    servingSize: "100 גרם",
    calories: 291,
    protein: 24,
    carbs: 0,
    fat: 21,
    fiber: 0,
  },
  {
    id: "f-usda-meat-009",
    name: "קבב בקר",
    englishName: "Beef Kebab",
    category: "בקר וכבש",
    servingSize: "100 גרם",
    calories: 234,
    protein: 22,
    carbs: 4,
    fat: 15,
    fiber: 0,
  },
  {
    id: "f-usda-meat-010",
    name: "המבורגר בקר",
    englishName: "Beef Burger Patty",
    category: "בקר וכבש",
    servingSize: "85 גרם",
    calories: 218,
    protein: 19,
    carbs: 0,
    fat: 15,
    fiber: 0,
  },
  {
    id: "f-usda-meat-011",
    name: "כבש קוסקוס",
    englishName: "Lamb Shoulder",
    category: "בקר וכבש",
    servingSize: "100 גרם",
    calories: 258,
    protein: 25,
    carbs: 0,
    fat: 17,
    fiber: 0,
  },
  {
    id: "f-usda-meat-012",
    name: "כבד עוף",
    englishName: "Chicken Liver",
    category: "עוף ועופות",
    servingSize: "85 גרם",
    calories: 142,
    protein: 20,
    carbs: 1,
    fat: 6,
    fiber: 0,
  },
  {
    id: "f-usda-meat-013",
    name: "בייקון",
    englishName: "Bacon",
    category: "בשר מעובד",
    servingSize: "2 רצועות (16 גרם)",
    calories: 87,
    protein: 6,
    carbs: 0,
    fat: 7,
    fiber: 0,
  },
  {
    id: "f-usda-meat-014",
    name: "נקניקיות",
    englishName: "Hot Dogs",
    category: "בשר מעובד",
    servingSize: "נקניקייה (45 גרם)",
    calories: 137,
    protein: 5,
    carbs: 2,
    fat: 12,
    fiber: 0,
  },
  {
    id: "f-usda-meat-015",
    name: "פפרוני",
    englishName: "Pepperoni",
    category: "בשר מעובד",
    servingSize: "17 פרוסות (30 גרם)",
    calories: 138,
    protein: 6,
    carbs: 1,
    fat: 13,
    fiber: 0,
  },
  {
    id: "f-usda-meat-016",
    name: "פרוסות הם",
    englishName: "Ham Slices",
    category: "בשר מעובד",
    servingSize: "2 פרוסות (56 גרם)",
    calories: 69,
    protein: 9,
    carbs: 2,
    fat: 3,
    fiber: 0,
  },
  {
    id: "f-usda-meat-017",
    name: "קורנד ביף",
    englishName: "Corned Beef",
    category: "בשר מעובד",
    servingSize: "85 גרם",
    calories: 213,
    protein: 15,
    carbs: 0,
    fat: 16,
    fiber: 0,
  },
  {
    id: "f-usda-meat-018",
    name: "חזה עוף מעושן",
    englishName: "Smoked Chicken Breast",
    category: "עוף ועופות",
    servingSize: "85 גרם",
    calories: 120,
    protein: 24,
    carbs: 1,
    fat: 2,
    fiber: 0,
  },
  {
    id: "f-usda-meat-019",
    name: "בריסקט",
    englishName: "Beef Brisket",
    category: "בקר וכבש",
    servingSize: "100 גרם",
    calories: 229,
    protein: 26,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  {
    id: "f-usda-meat-020",
    name: "ירך הודו",
    englishName: "Turkey Leg",
    category: "עוף ועופות",
    servingSize: "100 גרם",
    calories: 190,
    protein: 27,
    carbs: 0,
    fat: 9,
    fiber: 0,
  },

  // ── דגים ופירות ים ─────────────────────────────────────────────────────────
  {
    id: "f-usda-fish-001",
    name: "סלמון מוקפץ",
    englishName: "Pan-fried Salmon",
    category: "דגים",
    servingSize: "100 גרם",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
  },
  {
    id: "f-usda-fish-002",
    name: "טונה מקופסה שמן",
    englishName: "Canned Tuna in Oil",
    category: "דגים",
    servingSize: "100 גרם מסונן",
    calories: 198,
    protein: 26,
    carbs: 0,
    fat: 10,
    fiber: 0,
  },
  {
    id: "f-usda-fish-003",
    name: "שרימפס מבושל",
    englishName: "Cooked Shrimp",
    category: "פירות ים",
    servingSize: "85 גרם",
    calories: 84,
    protein: 18,
    carbs: 0,
    fat: 1,
    fiber: 0,
  },
  {
    id: "f-usda-fish-004",
    name: "הלבוט",
    englishName: "Halibut Fillet",
    category: "דגים",
    servingSize: "100 גרם",
    calories: 110,
    protein: 23,
    carbs: 0,
    fat: 2,
    fiber: 0,
  },
  {
    id: "f-usda-fish-005",
    name: "קוד",
    englishName: "Cod Fillet",
    category: "דגים",
    servingSize: "100 גרם",
    calories: 82,
    protein: 18,
    carbs: 0,
    fat: 1,
    fiber: 0,
  },
  {
    id: "f-usda-fish-006",
    name: "טילפיה",
    englishName: "Tilapia Fillet",
    category: "דגים",
    servingSize: "100 גרם",
    calories: 96,
    protein: 20,
    carbs: 0,
    fat: 2,
    fiber: 0,
  },
  {
    id: "f-usda-fish-007",
    name: "מקרל",
    englishName: "Mackerel",
    category: "דגים",
    servingSize: "100 גרם",
    calories: 205,
    protein: 19,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  {
    id: "f-usda-fish-008",
    name: "סרדינים בשמן",
    englishName: "Sardines in Oil",
    category: "דגים",
    servingSize: "100 גרם מסוננים",
    calories: 208,
    protein: 25,
    carbs: 0,
    fat: 11,
    fiber: 0,
  },
  {
    id: "f-usda-fish-009",
    name: "לברק ים",
    englishName: "Seabass",
    category: "דגים",
    servingSize: "100 גרם",
    calories: 124,
    protein: 24,
    carbs: 0,
    fat: 3,
    fiber: 0,
  },
  {
    id: "f-usda-fish-010",
    name: "אמנון",
    englishName: "St. Peter's Fish (Tilapia)",
    category: "דגים",
    servingSize: "100 גרם",
    calories: 96,
    protein: 20,
    carbs: 0,
    fat: 2,
    fiber: 0,
  },
  {
    id: "f-usda-fish-011",
    name: "קלמרי",
    englishName: "Squid / Calamari",
    category: "פירות ים",
    servingSize: "100 גרם",
    calories: 92,
    protein: 16,
    carbs: 3,
    fat: 1,
    fiber: 0,
  },
  {
    id: "f-usda-fish-012",
    name: "תמנון",
    englishName: "Octopus",
    category: "פירות ים",
    servingSize: "100 גרם",
    calories: 82,
    protein: 15,
    carbs: 2,
    fat: 1,
    fiber: 0,
  },
  {
    id: "f-usda-fish-013",
    name: "אנשובי",
    englishName: "Anchovies",
    category: "דגים",
    servingSize: "9 פילטים (20 גרם)",
    calories: 42,
    protein: 6,
    carbs: 0,
    fat: 2,
    fiber: 0,
  },
  {
    id: "f-usda-fish-014",
    name: "לוקוס",
    englishName: "Grouper",
    category: "דגים",
    servingSize: "100 גרם",
    calories: 92,
    protein: 20,
    carbs: 0,
    fat: 1,
    fiber: 0,
  },
  {
    id: "f-usda-fish-015",
    name: "אמנון מוקפץ בשמן",
    englishName: "Pan-fried Tilapia",
    category: "דגים",
    servingSize: "100 גרם",
    calories: 148,
    protein: 21,
    carbs: 0,
    fat: 7,
    fiber: 0,
  },

  // ── פירות ─────────────────────────────────────────────────────────────────
  {
    id: "f-usda-fruit-001",
    name: "אבטיח",
    englishName: "Watermelon",
    category: "פירות",
    servingSize: "2 פרוסות (280 גרם)",
    calories: 85,
    protein: 2,
    carbs: 21,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-fruit-002",
    name: "מנגו",
    englishName: "Mango",
    category: "פירות",
    servingSize: "פרי בינוני (200 גרם)",
    calories: 128,
    protein: 2,
    carbs: 32,
    fat: 1,
    fiber: 4,
  },
  {
    id: "f-usda-fruit-003",
    name: "אפרסק",
    englishName: "Peach",
    category: "פירות",
    servingSize: "פרי בינוני (150 גרם)",
    calories: 58,
    protein: 1,
    carbs: 14,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-fruit-004",
    name: "שזיף",
    englishName: "Plum",
    category: "פירות",
    servingSize: "פרי (85 גרם)",
    calories: 36,
    protein: 1,
    carbs: 9,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-fruit-005",
    name: "אוכמניות",
    englishName: "Blueberries",
    category: "פירות",
    servingSize: "חצי כוס (75 גרם)",
    calories: 42,
    protein: 1,
    carbs: 11,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-fruit-006",
    name: "אוכמניות קפואות",
    englishName: "Frozen Blueberries",
    category: "פירות",
    servingSize: "חצי כוס (78 גרם)",
    calories: 40,
    protein: 0,
    carbs: 10,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-fruit-007",
    name: "פאפאיה",
    englishName: "Papaya",
    category: "פירות",
    servingSize: "כוס קוביות (145 גרם)",
    calories: 62,
    protein: 1,
    carbs: 16,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-fruit-008",
    name: "פסיפלורה",
    englishName: "Passion Fruit",
    category: "פירות",
    servingSize: "פרי (18 גרם)",
    calories: 17,
    protein: 0,
    carbs: 4,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-fruit-009",
    name: "ספסבה",
    englishName: "Lychee",
    category: "פירות",
    servingSize: "10 פירות (100 גרם)",
    calories: 66,
    protein: 1,
    carbs: 17,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-fruit-010",
    name: "ג׳וז׳ובה",
    englishName: "Jujube",
    category: "פירות",
    servingSize: "3 פירות (30 גרם)",
    calories: 20,
    protein: 0,
    carbs: 5,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-fruit-011",
    name: "ענבים שחורים",
    englishName: "Black Grapes",
    category: "פירות",
    servingSize: "כוס (150 גרם)",
    calories: 104,
    protein: 1,
    carbs: 27,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-fruit-012",
    name: "ענבים ירוקים",
    englishName: "Green Grapes",
    category: "פירות",
    servingSize: "כוס (150 גרם)",
    calories: 104,
    protein: 1,
    carbs: 27,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-fruit-013",
    name: "קיווי",
    englishName: "Kiwi",
    category: "פירות",
    servingSize: "פרי (75 גרם)",
    calories: 46,
    protein: 1,
    carbs: 11,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-fruit-014",
    name: "מלון קנטלופ",
    englishName: "Cantaloupe",
    category: "פירות",
    servingSize: "כוס קוביות (160 גרם)",
    calories: 54,
    protein: 1,
    carbs: 13,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-fruit-015",
    name: "דובדבנים",
    englishName: "Cherries",
    category: "פירות",
    servingSize: "כוס (138 גרם)",
    calories: 87,
    protein: 1,
    carbs: 22,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-fruit-016",
    name: "תמרים מייג׳ול",
    englishName: "Medjool Dates",
    category: "פירות",
    servingSize: "2 תמרים (48 גרם)",
    calories: 133,
    protein: 1,
    carbs: 36,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-fruit-017",
    name: "פרי יבש צימוקים",
    englishName: "Raisins",
    category: "פירות",
    servingSize: "רבע כוס (41 גרם)",
    calories: 123,
    protein: 1,
    carbs: 33,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-fruit-018",
    name: "משמשים יבשים",
    englishName: "Dried Apricots",
    category: "פירות",
    servingSize: "6 יחידות (30 גרם)",
    calories: 72,
    protein: 1,
    carbs: 19,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-fruit-019",
    name: "שזיפים יבשים",
    englishName: "Prunes",
    category: "פירות",
    servingSize: "5 שזיפים (42 גרם)",
    calories: 101,
    protein: 1,
    carbs: 27,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-fruit-020",
    name: "פרי ד׳אנה",
    englishName: "Nectarine",
    category: "פירות",
    servingSize: "פרי (140 גרם)",
    calories: 63,
    protein: 2,
    carbs: 15,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-fruit-021",
    name: "רוכבת",
    englishName: "Blackberries",
    category: "פירות",
    servingSize: "כוס (144 גרם)",
    calories: 62,
    protein: 2,
    carbs: 14,
    fat: 1,
    fiber: 8,
  },
  {
    id: "f-usda-fruit-022",
    name: "פטל",
    englishName: "Raspberries",
    category: "פירות",
    servingSize: "כוס (123 גרם)",
    calories: 64,
    protein: 1,
    carbs: 15,
    fat: 1,
    fiber: 8,
  },
  {
    id: "f-usda-fruit-023",
    name: "גויאבה",
    englishName: "Guava",
    category: "פירות",
    servingSize: "פרי (90 גרם)",
    calories: 60,
    protein: 2,
    carbs: 14,
    fat: 1,
    fiber: 5,
  },
  {
    id: "f-usda-fruit-024",
    name: "פרי הדר ג׳ייפרוט",
    englishName: "Grapefruit",
    category: "פירות",
    servingSize: "חצי פרי (123 גרם)",
    calories: 41,
    protein: 1,
    carbs: 10,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-fruit-025",
    name: "קלמנטינה",
    englishName: "Clementine",
    category: "פירות",
    servingSize: "2 פירות (148 גרם)",
    calories: 70,
    protein: 1,
    carbs: 18,
    fat: 0,
    fiber: 2,
  },

  // ── ירקות ─────────────────────────────────────────────────────────────────
  {
    id: "f-usda-veg-001",
    name: "ארטישוק",
    englishName: "Artichoke",
    category: "ירקות",
    servingSize: "ארטישוק בינוני (120 גרם)",
    calories: 60,
    protein: 4,
    carbs: 13,
    fat: 0,
    fiber: 7,
  },
  {
    id: "f-usda-veg-002",
    name: "צנון",
    englishName: "Radish",
    category: "ירקות",
    servingSize: "10 צנונות (100 גרם)",
    calories: 16,
    protein: 1,
    carbs: 3,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-veg-003",
    name: "פנל",
    englishName: "Fennel",
    category: "ירקות",
    servingSize: "כוס פרוס (87 גרם)",
    calories: 27,
    protein: 1,
    carbs: 6,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-veg-004",
    name: "כרוב נירה",
    englishName: "Swiss Chard",
    category: "ירקות",
    servingSize: "כוס (36 גרם)",
    calories: 7,
    protein: 1,
    carbs: 1,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-veg-005",
    name: "כרישה",
    englishName: "Leek",
    category: "ירקות",
    servingSize: "כרישה בינונית (89 גרם)",
    calories: 54,
    protein: 1,
    carbs: 13,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-veg-006",
    name: "שורש סלרי",
    englishName: "Celeriac",
    category: "ירקות",
    servingSize: "כוס קוביות (156 גרם)",
    calories: 65,
    protein: 2,
    carbs: 14,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-veg-007",
    name: "ביצה חצילים",
    englishName: "Eggplant",
    category: "ירקות",
    servingSize: "כוס קוביות (82 גרם)",
    calories: 20,
    protein: 1,
    carbs: 5,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-veg-008",
    name: "סלק",
    englishName: "Beet Root",
    category: "ירקות",
    servingSize: "2 סלקים (100 גרם)",
    calories: 44,
    protein: 2,
    carbs: 10,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-veg-009",
    name: "לפת",
    englishName: "Turnip",
    category: "ירקות",
    servingSize: "כוס קוביות (130 גרם)",
    calories: 36,
    protein: 1,
    carbs: 8,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-veg-010",
    name: "אספרגוס",
    englishName: "Asparagus",
    category: "ירקות",
    servingSize: "5 גבעולים (90 גרם)",
    calories: 20,
    protein: 2,
    carbs: 4,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-veg-011",
    name: "שעועית ירוקה",
    englishName: "Green Beans",
    category: "ירקות",
    servingSize: "כוס (100 גרם)",
    calories: 31,
    protein: 2,
    carbs: 7,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-veg-012",
    name: "ארוגולה",
    englishName: "Arugula / Rocket",
    category: "ירקות",
    servingSize: "2 כוסות (40 גרם)",
    calories: 10,
    protein: 1,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-veg-013",
    name: "אנדיב",
    englishName: "Endive",
    category: "ירקות",
    servingSize: "כוס (50 גרם)",
    calories: 9,
    protein: 1,
    carbs: 2,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-veg-014",
    name: "חסה קוסי",
    englishName: "Romaine Lettuce",
    category: "ירקות",
    servingSize: "2 כוסות קצוצות (94 גרם)",
    calories: 16,
    protein: 1,
    carbs: 3,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-veg-015",
    name: "חסה גלגל",
    englishName: "Iceberg Lettuce",
    category: "ירקות",
    servingSize: "כוס (57 גרם)",
    calories: 8,
    protein: 1,
    carbs: 1,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-veg-016",
    name: "שעועית לימה",
    englishName: "Lima Beans",
    category: "ירקות",
    servingSize: "חצי כוס מבושל (90 גרם)",
    calories: 105,
    protein: 6,
    carbs: 20,
    fat: 0,
    fiber: 5,
  },
  {
    id: "f-usda-veg-017",
    name: "אפונה שלמה",
    englishName: "Whole Peas",
    category: "ירקות",
    servingSize: "חצי כוס (80 גרם)",
    calories: 59,
    protein: 4,
    carbs: 11,
    fat: 0,
    fiber: 4,
  },
  {
    id: "f-usda-veg-018",
    name: "תפוח אדמה מתוק",
    englishName: "Sweet Potato",
    category: "ירקות",
    servingSize: "בינוני (130 גרם)",
    calories: 112,
    protein: 2,
    carbs: 26,
    fat: 0,
    fiber: 4,
  },
  {
    id: "f-usda-veg-019",
    name: "דלורית",
    englishName: "Butternut Squash",
    category: "ירקות",
    servingSize: "כוס קוביות (140 גרם)",
    calories: 63,
    protein: 1,
    carbs: 16,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-veg-020",
    name: "פטרוזיליה",
    englishName: "Parsley",
    category: "ירקות",
    servingSize: "רבע כוס (15 גרם)",
    calories: 5,
    protein: 0,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-veg-021",
    name: "כוסברה",
    englishName: "Cilantro",
    category: "ירקות",
    servingSize: "רבע כוס (4 גרם)",
    calories: 1,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-veg-022",
    name: "בצל ירוק",
    englishName: "Scallion / Green Onion",
    category: "ירקות",
    servingSize: "כוס (100 גרם)",
    calories: 32,
    protein: 2,
    carbs: 7,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-veg-023",
    name: "פלפל ירוק",
    englishName: "Green Bell Pepper",
    category: "ירקות",
    servingSize: "פלפל בינוני (119 גרם)",
    calories: 24,
    protein: 1,
    carbs: 6,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-veg-024",
    name: "פלפל צהוב",
    englishName: "Yellow Bell Pepper",
    category: "ירקות",
    servingSize: "פלפל בינוני (186 גרם)",
    calories: 50,
    protein: 2,
    carbs: 12,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-veg-025",
    name: "פלפל חריף",
    englishName: "Jalapeño Pepper",
    category: "ירקות",
    servingSize: "פלפל (14 גרם)",
    calories: 4,
    protein: 0,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-veg-026",
    name: "פטריות שיטאקה",
    englishName: "Shiitake Mushrooms",
    category: "ירקות",
    servingSize: "כוס (145 גרם)",
    calories: 81,
    protein: 3,
    carbs: 21,
    fat: 0,
    fiber: 3,
  },
  {
    id: "f-usda-veg-027",
    name: "פטריות פורטבלו",
    englishName: "Portobello Mushrooms",
    category: "ירקות",
    servingSize: "כוס (121 גרם)",
    calories: 26,
    protein: 3,
    carbs: 5,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-veg-028",
    name: "אצות נורי",
    englishName: "Nori Seaweed",
    category: "ירקות",
    servingSize: "גיליון (2.5 גרם)",
    calories: 7,
    protein: 1,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-veg-029",
    name: "אדמה (פולי סויה)",
    englishName: "Edamame",
    category: "ירקות",
    servingSize: "חצי כוס (78 גרם)",
    calories: 94,
    protein: 9,
    carbs: 7,
    fat: 4,
    fiber: 4,
  },
  {
    id: "f-usda-veg-030",
    name: "שורש ג׳ינג׳ר",
    englishName: "Ginger Root",
    category: "ירקות",
    servingSize: "כפית מגוררת (2 גרם)",
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },

  // ── קטניות ודגנים ──────────────────────────────────────────────────────────
  {
    id: "f-usda-legume-001",
    name: "שעועית שחורה מבושלת",
    englishName: "Black Beans Cooked",
    category: "קטניות",
    servingSize: "חצי כוס (86 גרם)",
    calories: 114,
    protein: 8,
    carbs: 20,
    fat: 1,
    fiber: 7,
  },
  {
    id: "f-usda-legume-002",
    name: "שעועית כליות",
    englishName: "Kidney Beans Cooked",
    category: "קטניות",
    servingSize: "חצי כוס (88 גרם)",
    calories: 112,
    protein: 8,
    carbs: 20,
    fat: 0,
    fiber: 8,
  },
  {
    id: "f-usda-legume-003",
    name: "שעועית לבנה",
    englishName: "White Beans Cooked",
    category: "קטניות",
    servingSize: "חצי כוס (89 גרם)",
    calories: 125,
    protein: 9,
    carbs: 23,
    fat: 0,
    fiber: 6,
  },
  {
    id: "f-usda-legume-004",
    name: "עדשים ירוקות",
    englishName: "Green Lentils Cooked",
    category: "קטניות",
    servingSize: "חצי כוס (99 גרם)",
    calories: 115,
    protein: 9,
    carbs: 20,
    fat: 0,
    fiber: 8,
  },
  {
    id: "f-usda-legume-005",
    name: "אפונה מפוצלת",
    englishName: "Split Peas Cooked",
    category: "קטניות",
    servingSize: "חצי כוס (98 גרם)",
    calories: 116,
    protein: 8,
    carbs: 21,
    fat: 0,
    fiber: 8,
  },
  {
    id: "f-usda-legume-006",
    name: "פול מבושל",
    englishName: "Fava Beans Cooked",
    category: "קטניות",
    servingSize: "חצי כוס (85 גרם)",
    calories: 94,
    protein: 7,
    carbs: 17,
    fat: 0,
    fiber: 5,
  },
  {
    id: "f-usda-legume-007",
    name: "פינטו מבושל",
    englishName: "Pinto Beans Cooked",
    category: "קטניות",
    servingSize: "חצי כוס (86 גרם)",
    calories: 122,
    protein: 8,
    carbs: 22,
    fat: 1,
    fiber: 8,
  },
  {
    id: "f-usda-legume-008",
    name: "אורז בסמטי מבושל",
    englishName: "Basmati Rice Cooked",
    category: "דגנים",
    servingSize: "כוס (186 גרם)",
    calories: 238,
    protein: 5,
    carbs: 52,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-legume-009",
    name: "אורז חום מבושל",
    englishName: "Brown Rice Cooked",
    category: "דגנים",
    servingSize: "כוס (195 גרם)",
    calories: 216,
    protein: 5,
    carbs: 45,
    fat: 2,
    fiber: 4,
  },
  {
    id: "f-usda-legume-010",
    name: "קינואה מבושלת",
    englishName: "Quinoa Cooked",
    category: "דגנים",
    servingSize: "כוס (185 גרם)",
    calories: 222,
    protein: 8,
    carbs: 39,
    fat: 4,
    fiber: 5,
  },
  {
    id: "f-usda-legume-011",
    name: "בורגול מבושל",
    englishName: "Bulgur Cooked",
    category: "דגנים",
    servingSize: "כוס (182 גרם)",
    calories: 151,
    protein: 6,
    carbs: 34,
    fat: 0,
    fiber: 8,
  },
  {
    id: "f-usda-legume-012",
    name: "כוסמת מבושלת",
    englishName: "Buckwheat Cooked",
    category: "דגנים",
    servingSize: "כוס (168 גרם)",
    calories: 155,
    protein: 6,
    carbs: 33,
    fat: 1,
    fiber: 5,
  },
  {
    id: "f-usda-legume-013",
    name: "פסטה מחיטה מלאה",
    englishName: "Whole Wheat Pasta Cooked",
    category: "דגנים",
    servingSize: "כוס (140 גרם)",
    calories: 174,
    protein: 7,
    carbs: 37,
    fat: 1,
    fiber: 6,
  },
  {
    id: "f-usda-legume-014",
    name: "פסטה לבנה",
    englishName: "White Pasta Cooked",
    category: "דגנים",
    servingSize: "כוס (140 גרם)",
    calories: 220,
    protein: 8,
    carbs: 43,
    fat: 1,
    fiber: 3,
  },
  {
    id: "f-usda-legume-015",
    name: "אטריות שעועית",
    englishName: "Glass Noodles Cooked",
    category: "דגנים",
    servingSize: "כוס (140 גרם)",
    calories: 160,
    protein: 0,
    carbs: 39,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-legume-016",
    name: "ספגטי מלא",
    englishName: "Whole Wheat Spaghetti Cooked",
    category: "דגנים",
    servingSize: "כוס (140 גרם)",
    calories: 174,
    protein: 7,
    carbs: 37,
    fat: 1,
    fiber: 6,
  },
  {
    id: "f-usda-legume-017",
    name: "אורז יסמין",
    englishName: "Jasmine Rice Cooked",
    category: "דגנים",
    servingSize: "כוס (186 גרם)",
    calories: 238,
    protein: 4,
    carbs: 53,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-legume-018",
    name: "קוסקוס מבושל",
    englishName: "Couscous Cooked",
    category: "דגנים",
    servingSize: "כוס (157 גרם)",
    calories: 176,
    protein: 6,
    carbs: 36,
    fat: 0,
    fiber: 2,
  },

  // ── שמנים, אגוזים וזרעים ───────────────────────────────────────────────────
  {
    id: "f-usda-fat-001",
    name: "חמאת שקדים",
    englishName: "Almond Butter",
    category: "ממרחים",
    servingSize: "2 כפות (32 גרם)",
    calories: 196,
    protein: 7,
    carbs: 7,
    fat: 18,
    fiber: 2,
  },
  {
    id: "f-usda-fat-002",
    name: "חמאת קשיו",
    englishName: "Cashew Butter",
    category: "ממרחים",
    servingSize: "2 כפות (32 גרם)",
    calories: 188,
    protein: 6,
    carbs: 10,
    fat: 16,
    fiber: 1,
  },
  {
    id: "f-usda-fat-003",
    name: "שמן קוקוס",
    englishName: "Coconut Oil",
    category: "שמנים",
    servingSize: "כף (14 גרם)",
    calories: 121,
    protein: 0,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  {
    id: "f-usda-fat-004",
    name: "שמן אבוקדו",
    englishName: "Avocado Oil",
    category: "שמנים",
    servingSize: "כף (14 גרם)",
    calories: 124,
    protein: 0,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  {
    id: "f-usda-fat-005",
    name: "פיסטוקים",
    englishName: "Pistachios",
    category: "אגוזים",
    servingSize: "28 גרם (49 גרגרים)",
    calories: 159,
    protein: 6,
    carbs: 8,
    fat: 13,
    fiber: 3,
  },
  {
    id: "f-usda-fat-006",
    name: "אגוזי ברזיל",
    englishName: "Brazil Nuts",
    category: "אגוזים",
    servingSize: "6 אגוזים (28 גרם)",
    calories: 186,
    protein: 4,
    carbs: 3,
    fat: 19,
    fiber: 2,
  },
  {
    id: "f-usda-fat-007",
    name: "אגוזי לוז",
    englishName: "Hazelnuts",
    category: "אגוזים",
    servingSize: "28 גרם",
    calories: 178,
    protein: 4,
    carbs: 5,
    fat: 17,
    fiber: 3,
  },
  {
    id: "f-usda-fat-008",
    name: "אגוזי פקאן",
    englishName: "Pecans",
    category: "אגוזים",
    servingSize: "28 גרם",
    calories: 196,
    protein: 3,
    carbs: 4,
    fat: 20,
    fiber: 3,
  },
  {
    id: "f-usda-fat-009",
    name: "אגוזי מקדמיה",
    englishName: "Macadamia Nuts",
    category: "אגוזים",
    servingSize: "28 גרם",
    calories: 204,
    protein: 2,
    carbs: 4,
    fat: 21,
    fiber: 2,
  },
  {
    id: "f-usda-fat-010",
    name: "גרעיני דלעת",
    englishName: "Pumpkin Seeds",
    category: "אגוזים",
    servingSize: "28 גרם",
    calories: 151,
    protein: 7,
    carbs: 5,
    fat: 13,
    fiber: 2,
  },
  {
    id: "f-usda-fat-011",
    name: "זרעי פשתן",
    englishName: "Flaxseeds",
    category: "אגוזים",
    servingSize: "כף (10 גרם)",
    calories: 55,
    protein: 2,
    carbs: 3,
    fat: 4,
    fiber: 3,
  },
  {
    id: "f-usda-fat-012",
    name: "זרעי המפ",
    englishName: "Hemp Seeds",
    category: "אגוזים",
    servingSize: "3 כפות (30 גרם)",
    calories: 166,
    protein: 10,
    carbs: 3,
    fat: 15,
    fiber: 1,
  },
  {
    id: "f-usda-fat-013",
    name: "שמן חמניות",
    englishName: "Sunflower Oil",
    category: "שמנים",
    servingSize: "כף (14 גרם)",
    calories: 124,
    protein: 0,
    carbs: 0,
    fat: 14,
    fiber: 0,
  },
  {
    id: "f-usda-fat-014",
    name: "חמאת בוטנים טבעית",
    englishName: "Natural Peanut Butter",
    category: "ממרחים",
    servingSize: "2 כפות (32 גרם)",
    calories: 191,
    protein: 8,
    carbs: 7,
    fat: 16,
    fiber: 2,
  },
  {
    id: "f-usda-fat-015",
    name: "גרעיני חמניות",
    englishName: "Sunflower Seeds",
    category: "אגוזים",
    servingSize: "28 גרם",
    calories: 163,
    protein: 6,
    carbs: 6,
    fat: 14,
    fiber: 3,
  },

  // ── מוצרי סויה ואלטרנטיביות ────────────────────────────────────────────────
  {
    id: "f-usda-soy-001",
    name: "טופו קשה",
    englishName: "Firm Tofu",
    category: "מוצרים צמחיים",
    servingSize: "100 גרם",
    calories: 76,
    protein: 9,
    carbs: 2,
    fat: 4,
    fiber: 0,
  },
  {
    id: "f-usda-soy-002",
    name: "טופו רך",
    englishName: "Silken Tofu",
    category: "מוצרים צמחיים",
    servingSize: "100 גרם",
    calories: 55,
    protein: 5,
    carbs: 2,
    fat: 3,
    fiber: 0,
  },
  {
    id: "f-usda-soy-003",
    name: "טמפה",
    englishName: "Tempeh",
    category: "מוצרים צמחיים",
    servingSize: "100 גרם",
    calories: 193,
    protein: 19,
    carbs: 8,
    fat: 11,
    fiber: 5,
  },
  {
    id: "f-usda-soy-004",
    name: "אדמה קפוא",
    englishName: "Frozen Edamame Shelled",
    category: "מוצרים צמחיים",
    servingSize: "חצי כוס (78 גרם)",
    calories: 94,
    protein: 9,
    carbs: 7,
    fat: 4,
    fiber: 4,
  },
  {
    id: "f-usda-soy-005",
    name: "יוגורט סויה",
    englishName: "Soy Yogurt",
    category: "מוצרים צמחיים",
    servingSize: "170 גרם",
    calories: 130,
    protein: 6,
    carbs: 16,
    fat: 4,
    fiber: 1,
  },
  {
    id: "f-usda-soy-006",
    name: "המבורגר צמחי",
    englishName: "Plant-based Burger Patty",
    category: "מוצרים צמחיים",
    servingSize: "113 גרם",
    calories: 230,
    protein: 20,
    carbs: 9,
    fat: 13,
    fiber: 3,
  },
  {
    id: "f-usda-soy-007",
    name: "נקניקיית סויה",
    englishName: "Soy Sausage",
    category: "מוצרים צמחיים",
    servingSize: "2 נקניקיות (76 גרם)",
    calories: 160,
    protein: 15,
    carbs: 7,
    fat: 8,
    fiber: 2,
  },
  {
    id: "f-usda-soy-008",
    name: "חלב סויה",
    englishName: "Soy Milk",
    category: "מוצרים צמחיים",
    servingSize: "כוס (240 מ״ל)",
    calories: 80,
    protein: 7,
    carbs: 4,
    fat: 4,
    fiber: 0,
  },
  {
    id: "f-usda-soy-009",
    name: "גבינת טופו",
    englishName: "Tofu Cream Cheese",
    category: "מוצרים צמחיים",
    servingSize: "2 כפות (30 גרם)",
    calories: 50,
    protein: 2,
    carbs: 2,
    fat: 4,
    fiber: 0,
  },
  {
    id: "f-usda-soy-010",
    name: "פרוטאין אפונה",
    englishName: "Pea Protein Shake",
    category: "מוצרים צמחיים",
    servingSize: "גביע (240 מ״ל)",
    calories: 130,
    protein: 20,
    carbs: 5,
    fat: 3,
    fiber: 1,
  },

  // ── חטיפים מלוחים ──────────────────────────────────────────────────────────
  {
    id: "f-usda-snack-001",
    name: "צ׳יפס תפו״א קלאסי",
    englishName: "Potato Chips Classic",
    category: "חטיפים",
    servingSize: "28 גרם (15 שבבים)",
    calories: 153,
    protein: 2,
    carbs: 15,
    fat: 10,
    fiber: 1,
  },
  {
    id: "f-usda-snack-002",
    name: "דורים טורטייה",
    englishName: "Tortilla Chips",
    category: "חטיפים",
    servingSize: "28 גרם (11 שבבים)",
    calories: 138,
    protein: 2,
    carbs: 19,
    fat: 7,
    fiber: 1,
  },
  {
    id: "f-usda-snack-003",
    name: "צ׳יפס תפו״א מלח ים",
    englishName: "Sea Salt Potato Chips",
    category: "חטיפים",
    servingSize: "28 גרם",
    calories: 150,
    protein: 2,
    carbs: 15,
    fat: 10,
    fiber: 1,
  },
  {
    id: "f-usda-snack-004",
    name: "פופקורן חמאה",
    englishName: "Butter Popcorn",
    category: "חטיפים",
    servingSize: "3 כוסות מוכן (30 גרם)",
    calories: 161,
    protein: 2,
    carbs: 19,
    fat: 9,
    fiber: 3,
  },
  {
    id: "f-usda-snack-005",
    name: "פופקורן אוויר",
    englishName: "Air-popped Popcorn",
    category: "חטיפים",
    servingSize: "3 כוסות (24 גרם)",
    calories: 93,
    protein: 3,
    carbs: 19,
    fat: 1,
    fiber: 4,
  },
  {
    id: "f-usda-snack-006",
    name: "אורז מתופח",
    englishName: "Rice Cakes (plain)",
    category: "חטיפים",
    servingSize: "2 דיסקיות (18 גרם)",
    calories: 70,
    protein: 1,
    carbs: 15,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-snack-007",
    name: "פרצלים מלוחים",
    englishName: "Pretzel Sticks",
    category: "חטיפים",
    servingSize: "28 גרם",
    calories: 109,
    protein: 3,
    carbs: 23,
    fat: 1,
    fiber: 1,
  },
  {
    id: "f-usda-snack-008",
    name: "גרנולה בר",
    englishName: "Granola Bar",
    category: "חטיפים",
    servingSize: "בר (40 גרם)",
    calories: 190,
    protein: 4,
    carbs: 29,
    fat: 7,
    fiber: 2,
  },
  {
    id: "f-usda-snack-009",
    name: "בר חלבון",
    englishName: "Protein Bar",
    category: "חטיפים",
    servingSize: "בר (68 גרם)",
    calories: 260,
    protein: 20,
    carbs: 28,
    fat: 7,
    fiber: 2,
  },
  {
    id: "f-usda-snack-010",
    name: "עוגיות שיבולת שועל",
    englishName: "Oatmeal Cookies",
    category: "חטיפים",
    servingSize: "2 עוגיות (52 גרם)",
    calories: 234,
    protein: 3,
    carbs: 34,
    fat: 10,
    fiber: 2,
  },
  {
    id: "f-usda-snack-011",
    name: "קרקרים ריץ׳",
    englishName: "Ritz Crackers",
    category: "חטיפים",
    servingSize: "5 קרקרים (16 גרם)",
    calories: 79,
    protein: 1,
    carbs: 10,
    fat: 4,
    fiber: 0,
  },
  {
    id: "f-usda-snack-012",
    name: "טורטייה שבבים נאצ׳וס",
    englishName: "Nacho Flavored Tortilla Chips",
    category: "חטיפים",
    servingSize: "28 גרם",
    calories: 140,
    protein: 2,
    carbs: 19,
    fat: 6,
    fiber: 1,
  },
  {
    id: "f-usda-snack-013",
    name: "חטיף בר אנרגיה",
    englishName: "Energy Bar",
    category: "חטיפים",
    servingSize: "בר (45 גרם)",
    calories: 200,
    protein: 8,
    carbs: 29,
    fat: 6,
    fiber: 3,
  },
  {
    id: "f-usda-snack-014",
    name: "שבבי תפו״א אפוי",
    englishName: "Baked Potato Chips",
    category: "חטיפים",
    servingSize: "28 גרם",
    calories: 110,
    protein: 2,
    carbs: 22,
    fat: 2,
    fiber: 2,
  },
  {
    id: "f-usda-snack-015",
    name: "חמוציות מיובשות",
    englishName: "Dried Cranberries",
    category: "חטיפים",
    servingSize: "רבע כוס (30 גרם)",
    calories: 92,
    protein: 0,
    carbs: 25,
    fat: 0,
    fiber: 1,
  },

  // ── גלידות וקינוחים קפואים ─────────────────────────────────────────────────
  {
    id: "f-usda-ice-001",
    name: "גלידת סנדוויץ׳",
    englishName: "Ice Cream Sandwich",
    category: "ממתקים וקינוחים",
    servingSize: "סנדוויץ׳ (65 גרם)",
    calories: 190,
    protein: 3,
    carbs: 31,
    fat: 6,
    fiber: 1,
    searchTerms: ["ice cream sandwich", "גלידה קרח", "סנדביץ גלידה"],
  },
  {
    id: "f-usda-ice-002",
    name: "גלידת וניל",
    englishName: "Vanilla Ice Cream",
    category: "ממתקים וקינוחים",
    servingSize: "גביע (70 גרם)",
    calories: 145,
    protein: 2,
    carbs: 19,
    fat: 7,
    fiber: 0,
  },
  {
    id: "f-usda-ice-003",
    name: "גלידת שוקולד",
    englishName: "Chocolate Ice Cream",
    category: "ממתקים וקינוחים",
    servingSize: "גביע (70 גרם)",
    calories: 153,
    protein: 3,
    carbs: 21,
    fat: 7,
    fiber: 1,
  },
  {
    id: "f-usda-ice-004",
    name: "גלידת תות",
    englishName: "Strawberry Ice Cream",
    category: "ממתקים וקינוחים",
    servingSize: "גביע (70 גרם)",
    calories: 140,
    protein: 2,
    carbs: 20,
    fat: 6,
    fiber: 0,
  },
  {
    id: "f-usda-ice-005",
    name: "פרוזן יוגורט",
    englishName: "Frozen Yogurt",
    category: "ממתקים וקינוחים",
    servingSize: "100 גרם",
    calories: 127,
    protein: 3,
    carbs: 23,
    fat: 3,
    fiber: 0,
  },
  {
    id: "f-usda-ice-006",
    name: "שרבט תות",
    englishName: "Strawberry Sorbet",
    category: "ממתקים וקינוחים",
    servingSize: "100 גרם",
    calories: 120,
    protein: 0,
    carbs: 30,
    fat: 0,
    fiber: 1,
  },
  {
    id: "f-usda-ice-007",
    name: "ארטיק מיץ",
    englishName: "Juice Popsicle",
    category: "ממתקים וקינוחים",
    servingSize: "ארטיק (80 גרם)",
    calories: 43,
    protein: 0,
    carbs: 11,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-ice-008",
    name: "גלידת פיסטוק",
    englishName: "Pistachio Ice Cream",
    category: "ממתקים וקינוחים",
    servingSize: "גביע (70 גרם)",
    calories: 155,
    protein: 3,
    carbs: 18,
    fat: 8,
    fiber: 0,
  },
  {
    id: "f-usda-ice-009",
    name: "גלידת מנגו טבעוני",
    englishName: "Vegan Mango Ice Cream",
    category: "ממתקים וקינוחים",
    servingSize: "100 גרם",
    calories: 145,
    protein: 1,
    carbs: 26,
    fat: 5,
    fiber: 1,
  },
  {
    id: "f-usda-ice-010",
    name: "מגנום שוקולד",
    englishName: "Chocolate Coated Ice Cream Bar",
    category: "ממתקים וקינוחים",
    servingSize: "אחד (88 גרם)",
    calories: 260,
    protein: 3,
    carbs: 25,
    fat: 16,
    fiber: 1,
  },

  // ── ממתקים ───────────────────────────────────────────────────────────────
  {
    id: "f-usda-sweet-001",
    name: "שוקולד מריר 70%",
    englishName: "Dark Chocolate 70%",
    category: "ממתקים וקינוחים",
    servingSize: "28 גרם (2 קוביות)",
    calories: 167,
    protein: 2,
    carbs: 14,
    fat: 12,
    fiber: 3,
  },
  {
    id: "f-usda-sweet-002",
    name: "שוקולד חלב",
    englishName: "Milk Chocolate",
    category: "ממתקים וקינוחים",
    servingSize: "28 גרם",
    calories: 153,
    protein: 2,
    carbs: 17,
    fat: 9,
    fiber: 1,
  },
  {
    id: "f-usda-sweet-003",
    name: "ממתק מ&מ׳ס",
    englishName: "M&M's",
    category: "ממתקים וקינוחים",
    servingSize: "32 גרם (1 חפיסה)",
    calories: 160,
    protein: 2,
    carbs: 23,
    fat: 7,
    fiber: 1,
  },
  {
    id: "f-usda-sweet-004",
    name: "ממתק ריסס",
    englishName: "Reese's Peanut Butter Cup",
    category: "ממתקים וקינוחים",
    servingSize: "2 גביעים (42 גרם)",
    calories: 218,
    protein: 4,
    carbs: 23,
    fat: 13,
    fiber: 1,
  },
  {
    id: "f-usda-sweet-005",
    name: "ממתק סניקרס",
    englishName: "Snickers Bar",
    category: "ממתקים וקינוחים",
    servingSize: "57 גרם",
    calories: 280,
    protein: 4,
    carbs: 37,
    fat: 14,
    fiber: 1,
  },
  {
    id: "f-usda-sweet-006",
    name: "ממתק קיט קאט",
    englishName: "Kit Kat Bar",
    category: "ממתקים וקינוחים",
    servingSize: "45 גרם (4 יחידות)",
    calories: 218,
    protein: 3,
    carbs: 28,
    fat: 11,
    fiber: 1,
  },
  {
    id: "f-usda-sweet-007",
    name: "מרשמלוס",
    englishName: "Marshmallows",
    category: "ממתקים וקינוחים",
    servingSize: "4 גדולים (28 גרם)",
    calories: 91,
    protein: 1,
    carbs: 23,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-sweet-008",
    name: "בראוני שוקולד",
    englishName: "Brownie",
    category: "ממתקים וקינוחים",
    servingSize: "חתיכה (56 גרם)",
    calories: 243,
    protein: 3,
    carbs: 35,
    fat: 11,
    fiber: 2,
  },
  {
    id: "f-usda-sweet-009",
    name: "עוגיית שוקולד צ׳יפ",
    englishName: "Chocolate Chip Cookie",
    category: "ממתקים וקינוחים",
    servingSize: "עוגייה גדולה (40 גרם)",
    calories: 193,
    protein: 2,
    carbs: 26,
    fat: 9,
    fiber: 1,
  },
  {
    id: "f-usda-sweet-010",
    name: "עוגיית אוריאו",
    englishName: "Oreo Cookies",
    category: "ממתקים וקינוחים",
    servingSize: "3 עוגיות (34 גרם)",
    calories: 160,
    protein: 2,
    carbs: 25,
    fat: 7,
    fiber: 1,
  },
  {
    id: "f-usda-sweet-011",
    name: "עוגת גבינה",
    englishName: "Cheesecake",
    category: "ממתקים וקינוחים",
    servingSize: "פרוסה (125 גרם)",
    calories: 403,
    protein: 7,
    carbs: 33,
    fat: 28,
    fiber: 1,
  },
  {
    id: "f-usda-sweet-012",
    name: "עוגת שוקולד",
    englishName: "Chocolate Cake with Frosting",
    category: "ממתקים וקינוחים",
    servingSize: "פרוסה (100 גרם)",
    calories: 370,
    protein: 4,
    carbs: 53,
    fat: 17,
    fiber: 2,
  },
  {
    id: "f-usda-sweet-013",
    name: "מאפין שוקולד",
    englishName: "Chocolate Muffin",
    category: "ממתקים וקינוחים",
    servingSize: "מאפין (113 גרם)",
    calories: 424,
    protein: 6,
    carbs: 55,
    fat: 21,
    fiber: 2,
  },
  {
    id: "f-usda-sweet-014",
    name: "ג׳לי",
    englishName: "Jello / Gelatin",
    category: "ממתקים וקינוחים",
    servingSize: "חצי כוס (140 גרם)",
    calories: 80,
    protein: 2,
    carbs: 19,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-sweet-015",
    name: "פודינג שוקולד",
    englishName: "Chocolate Pudding",
    category: "ממתקים וקינוחים",
    servingSize: "חצי כוס (142 גרם)",
    calories: 155,
    protein: 4,
    carbs: 26,
    fat: 4,
    fiber: 1,
  },

  // ── משקאות ───────────────────────────────────────────────────────────────
  {
    id: "f-usda-bev-001",
    name: "קפה שחור",
    englishName: "Black Coffee",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-002",
    name: "אמריקנו",
    englishName: "Americano",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 15,
    protein: 0,
    carbs: 2,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-003",
    name: "לאטה רגיל",
    englishName: "Latte (whole milk)",
    category: "משקאות",
    servingSize: "כוס גדולה (360 מ״ל)",
    calories: 190,
    protein: 12,
    carbs: 19,
    fat: 7,
    fiber: 0,
  },
  {
    id: "f-usda-bev-004",
    name: "לאטה רזה",
    englishName: "Latte (skim milk)",
    category: "משקאות",
    servingSize: "כוס גדולה (360 מ״ל)",
    calories: 130,
    protein: 13,
    carbs: 19,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-005",
    name: "קפוצ׳ינו",
    englishName: "Cappuccino",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 80,
    protein: 5,
    carbs: 8,
    fat: 3,
    fiber: 0,
  },
  {
    id: "f-usda-bev-006",
    name: "קרם ברולה לאטה",
    englishName: "Flavored Latte",
    category: "משקאות",
    servingSize: "כוס גדולה (360 מ״ל)",
    calories: 250,
    protein: 12,
    carbs: 37,
    fat: 6,
    fiber: 0,
  },
  {
    id: "f-usda-bev-007",
    name: "קולה",
    englishName: "Coca-Cola",
    category: "משקאות",
    servingSize: "פחית (355 מ״ל)",
    calories: 140,
    protein: 0,
    carbs: 39,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-008",
    name: "קולה דיאט",
    englishName: "Diet Coke",
    category: "משקאות",
    servingSize: "פחית (355 מ״ל)",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-009",
    name: "ספרייט",
    englishName: "Sprite",
    category: "משקאות",
    servingSize: "פחית (355 מ״ל)",
    calories: 140,
    protein: 0,
    carbs: 38,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-010",
    name: "מיץ תפוחים",
    englishName: "Apple Juice",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 114,
    protein: 0,
    carbs: 28,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-011",
    name: "מיץ תפוזים",
    englishName: "Orange Juice",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 112,
    protein: 2,
    carbs: 26,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-012",
    name: "מיץ גזר",
    englishName: "Carrot Juice",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 94,
    protein: 2,
    carbs: 22,
    fat: 0,
    fiber: 2,
  },
  {
    id: "f-usda-bev-013",
    name: "חלב שוקולד",
    englishName: "Chocolate Milk",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 208,
    protein: 8,
    carbs: 32,
    fat: 5,
    fiber: 1,
  },
  {
    id: "f-usda-bev-014",
    name: "חלב שוקולד דל שומן",
    englishName: "Low Fat Chocolate Milk",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 158,
    protein: 8,
    carbs: 26,
    fat: 3,
    fiber: 1,
  },
  {
    id: "f-usda-bev-015",
    name: "תה ירוק",
    englishName: "Green Tea",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-016",
    name: "תה שחור",
    englishName: "Black Tea",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-017",
    name: "תה קמומיל",
    englishName: "Chamomile Tea",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 2,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-018",
    name: "מיץ ענבים",
    englishName: "Grape Juice",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 152,
    protein: 1,
    carbs: 37,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bev-019",
    name: "שייק בננה",
    englishName: "Banana Milk Shake",
    category: "משקאות",
    servingSize: "כוס (300 מ״ל)",
    calories: 270,
    protein: 8,
    carbs: 44,
    fat: 7,
    fiber: 1,
  },
  {
    id: "f-usda-bev-020",
    name: "מי ברז רגילים",
    englishName: "Tap Water",
    category: "משקאות",
    servingSize: "כוס (240 מ״ל)",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },

  // ── רטבים ותבלינים ────────────────────────────────────────────────────────
  {
    id: "f-usda-sauce-001",
    name: "קטשופ",
    englishName: "Ketchup",
    category: "רטבים",
    servingSize: "כף (17 גרם)",
    calories: 17,
    protein: 0,
    carbs: 4,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-002",
    name: "מיונז רגיל",
    englishName: "Mayonnaise",
    category: "רטבים",
    servingSize: "כף (14 גרם)",
    calories: 94,
    protein: 0,
    carbs: 0,
    fat: 10,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-003",
    name: "מיונז לייט",
    englishName: "Light Mayonnaise",
    category: "רטבים",
    servingSize: "כף (15 גרם)",
    calories: 49,
    protein: 0,
    carbs: 1,
    fat: 5,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-004",
    name: "רוטב ברביקיו",
    englishName: "BBQ Sauce",
    category: "רטבים",
    servingSize: "2 כפות (36 גרם)",
    calories: 58,
    protein: 0,
    carbs: 14,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-005",
    name: "רוטב סויה",
    englishName: "Soy Sauce",
    category: "רטבים",
    servingSize: "כף (16 גרם)",
    calories: 9,
    protein: 1,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-006",
    name: "סוג מתוק לאנה",
    englishName: "Sweet Chili Sauce",
    category: "רטבים",
    servingSize: "2 כפות (32 גרם)",
    calories: 60,
    protein: 0,
    carbs: 15,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-007",
    name: "פסטו",
    englishName: "Pesto Sauce",
    category: "רטבים",
    servingSize: "2 כפות (30 גרם)",
    calories: 120,
    protein: 2,
    carbs: 3,
    fat: 12,
    fiber: 1,
  },
  {
    id: "f-usda-sauce-008",
    name: "רוטב עגבניות",
    englishName: "Marinara Sauce",
    category: "רטבים",
    servingSize: "חצי כוס (125 גרם)",
    calories: 70,
    protein: 2,
    carbs: 10,
    fat: 2,
    fiber: 2,
  },
  {
    id: "f-usda-sauce-009",
    name: "חרדל דיז׳ון",
    englishName: "Dijon Mustard",
    category: "רטבים",
    servingSize: "כפית (5 גרם)",
    calories: 5,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-010",
    name: "רוטב יוגורט",
    englishName: "Tzatziki / Yogurt Dip",
    category: "רטבים",
    servingSize: "2 כפות (30 גרם)",
    calories: 35,
    protein: 2,
    carbs: 2,
    fat: 2,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-011",
    name: "חמאה",
    englishName: "Butter",
    category: "שמנים",
    servingSize: "כף (14 גרם)",
    calories: 102,
    protein: 0,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-012",
    name: "חמאה מלוחה",
    englishName: "Salted Butter",
    category: "שמנים",
    servingSize: "כף (14 גרם)",
    calories: 102,
    protein: 0,
    carbs: 0,
    fat: 12,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-013",
    name: "מרגרינה",
    englishName: "Margarine",
    category: "שמנים",
    servingSize: "כף (14 גרם)",
    calories: 101,
    protein: 0,
    carbs: 0,
    fat: 11,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-014",
    name: "רוטב חריף",
    englishName: "Hot Sauce / Sriracha",
    category: "רטבים",
    servingSize: "כפית (5 גרם)",
    calories: 5,
    protein: 0,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-sauce-015",
    name: "וויסטרשייר",
    englishName: "Worcestershire Sauce",
    category: "רטבים",
    servingSize: "כף (17 גרם)",
    calories: 13,
    protein: 0,
    carbs: 3,
    fat: 0,
    fiber: 0,
  },

  // ── אוכל מהיר ─────────────────────────────────────────────────────────────
  {
    id: "f-usda-fast-001",
    name: "המבורגר כפול בייקון",
    englishName: "Double Bacon Cheeseburger",
    category: "אוכל מהיר",
    servingSize: "המבורגר (220 גרם)",
    calories: 590,
    protein: 34,
    carbs: 41,
    fat: 32,
    fiber: 2,
  },
  {
    id: "f-usda-fast-002",
    name: "פיצה מרגריטה",
    englishName: "Margherita Pizza Slice",
    category: "אוכל מהיר",
    servingSize: "פרוסה (107 גרם)",
    calories: 272,
    protein: 12,
    carbs: 34,
    fat: 10,
    fiber: 2,
  },
  {
    id: "f-usda-fast-003",
    name: "פיצה פפרוני",
    englishName: "Pepperoni Pizza Slice",
    category: "אוכל מהיר",
    servingSize: "פרוסה (113 גרם)",
    calories: 313,
    protein: 14,
    carbs: 34,
    fat: 13,
    fiber: 2,
  },
  {
    id: "f-usda-fast-004",
    name: "ביג מק",
    englishName: "Big Mac Burger",
    category: "אוכל מהיר",
    servingSize: "המבורגר (215 גרם)",
    calories: 550,
    protein: 25,
    carbs: 45,
    fat: 30,
    fiber: 3,
  },
  {
    id: "f-usda-fast-005",
    name: "צ׳יפס מקדונלד׳ס גדול",
    englishName: "McDonald's Large Fries",
    category: "אוכל מהיר",
    servingSize: "מנה (154 גרם)",
    calories: 490,
    protein: 7,
    carbs: 66,
    fat: 23,
    fiber: 6,
  },
  {
    id: "f-usda-fast-006",
    name: "צ׳יפס בינוני",
    englishName: "Medium French Fries",
    category: "אוכל מהיר",
    servingSize: "מנה (113 גרם)",
    calories: 365,
    protein: 4,
    carbs: 48,
    fat: 17,
    fiber: 4,
  },
  {
    id: "f-usda-fast-007",
    name: "צ׳יקן מק׳נגטס",
    englishName: "Chicken McNuggets (6 pcs)",
    category: "אוכל מהיר",
    servingSize: "6 יחידות (98 גרם)",
    calories: 250,
    protein: 15,
    carbs: 15,
    fat: 15,
    fiber: 0,
  },
  {
    id: "f-usda-fast-008",
    name: "בוריטו תרנגול",
    englishName: "Chicken Burrito",
    category: "אוכל מהיר",
    servingSize: "בוריטו (300 גרם)",
    calories: 568,
    protein: 32,
    carbs: 65,
    fat: 19,
    fiber: 6,
  },
  {
    id: "f-usda-fast-009",
    name: "טאקו עוף",
    englishName: "Chicken Taco",
    category: "אוכל מהיר",
    servingSize: "טאקו (170 גרם)",
    calories: 340,
    protein: 22,
    carbs: 30,
    fat: 14,
    fiber: 3,
  },
  {
    id: "f-usda-fast-010",
    name: "כריך BLT",
    englishName: "BLT Sandwich",
    category: "אוכל מהיר",
    servingSize: "כריך (145 גרם)",
    calories: 340,
    protein: 14,
    carbs: 28,
    fat: 19,
    fiber: 2,
  },
  {
    id: "f-usda-fast-011",
    name: "כריך קלאב",
    englishName: "Club Sandwich",
    category: "אוכל מהיר",
    servingSize: "כריך (250 גרם)",
    calories: 543,
    protein: 34,
    carbs: 43,
    fat: 25,
    fiber: 3,
  },
  {
    id: "f-usda-fast-012",
    name: "פה פיצה מלאה",
    englishName: "Calzone",
    category: "אוכל מהיר",
    servingSize: "קלצונה (300 גרם)",
    calories: 783,
    protein: 37,
    carbs: 85,
    fat: 31,
    fiber: 5,
  },
  {
    id: "f-usda-fast-013",
    name: "נאגטס עוף קפוא",
    englishName: "Frozen Chicken Nuggets",
    category: "אוכל מהיר",
    servingSize: "6 יחידות (86 גרם)",
    calories: 200,
    protein: 13,
    carbs: 14,
    fat: 10,
    fiber: 0,
  },
  {
    id: "f-usda-fast-014",
    name: "פלאפל בפיתה",
    englishName: "Falafel in Pita",
    category: "אוכל מהיר",
    servingSize: "פיתה (250 גרם)",
    calories: 490,
    protein: 19,
    carbs: 62,
    fat: 19,
    fiber: 9,
  },
  {
    id: "f-usda-fast-015",
    name: "שווארמה עוף בפיתה",
    englishName: "Chicken Shawarma Pita",
    category: "אוכל מהיר",
    servingSize: "פיתה (280 גרם)",
    calories: 520,
    protein: 40,
    carbs: 50,
    fat: 16,
    fiber: 4,
  },
  {
    id: "f-usda-fast-016",
    name: "בורגר צמחוני",
    englishName: "Veggie Burger",
    category: "אוכל מהיר",
    servingSize: "המבורגר (150 גרם)",
    calories: 350,
    protein: 20,
    carbs: 38,
    fat: 13,
    fiber: 5,
  },
  {
    id: "f-usda-fast-017",
    name: "פשטידת קינואה",
    englishName: "Quinoa Bowl",
    category: "אוכל מהיר",
    servingSize: "מנה (300 גרם)",
    calories: 420,
    protein: 18,
    carbs: 60,
    fat: 12,
    fiber: 8,
  },
  {
    id: "f-usda-fast-018",
    name: "סלט קיסר עם עוף",
    englishName: "Caesar Salad with Chicken",
    category: "אוכל מהיר",
    servingSize: "מנה (300 גרם)",
    calories: 430,
    protein: 33,
    carbs: 18,
    fat: 26,
    fiber: 3,
  },
  {
    id: "f-usda-fast-019",
    name: "ספגטי בולונז",
    englishName: "Spaghetti Bolognese",
    category: "אוכל מהיר",
    servingSize: "מנה (320 גרם)",
    calories: 490,
    protein: 28,
    carbs: 62,
    fat: 14,
    fiber: 5,
  },
  {
    id: "f-usda-fast-020",
    name: "תוספת אורז",
    englishName: "Side of Rice",
    category: "אוכל מהיר",
    servingSize: "מנה (185 גרם)",
    calories: 240,
    protein: 4,
    carbs: 52,
    fat: 0,
    fiber: 1,
  },

  // ── ארוחות מוכנות ──────────────────────────────────────────────────────────
  {
    id: "f-usda-ready-001",
    name: "מרק עדשים",
    englishName: "Lentil Soup",
    category: "ארוחות מוכנות",
    servingSize: "קערה (245 גרם)",
    calories: 199,
    protein: 14,
    carbs: 34,
    fat: 2,
    fiber: 12,
  },
  {
    id: "f-usda-ready-002",
    name: "מרק עגבניות",
    englishName: "Tomato Soup",
    category: "ארוחות מוכנות",
    servingSize: "קערה (245 גרם)",
    calories: 85,
    protein: 2,
    carbs: 17,
    fat: 2,
    fiber: 1,
  },
  {
    id: "f-usda-ready-003",
    name: "מרק עוף עם אטריות",
    englishName: "Chicken Noodle Soup",
    category: "ארוחות מוכנות",
    servingSize: "קערה (245 גרם)",
    calories: 75,
    protein: 5,
    carbs: 10,
    fat: 2,
    fiber: 1,
  },
  {
    id: "f-usda-ready-004",
    name: "מרק מינסטרונה",
    englishName: "Minestrone Soup",
    category: "ארוחות מוכנות",
    servingSize: "קערה (245 גרם)",
    calories: 81,
    protein: 4,
    carbs: 12,
    fat: 1,
    fiber: 3,
  },
  {
    id: "f-usda-ready-005",
    name: "צ׳ילי קון קרנה",
    englishName: "Chili con Carne",
    category: "ארוחות מוכנות",
    servingSize: "כוס (253 גרם)",
    calories: 287,
    protein: 20,
    carbs: 28,
    fat: 10,
    fiber: 9,
  },
  {
    id: "f-usda-ready-006",
    name: "שקשוקה",
    englishName: "Shakshuka",
    category: "ארוחות מוכנות",
    servingSize: "מנה (250 גרם)",
    calories: 210,
    protein: 14,
    carbs: 14,
    fat: 11,
    fiber: 3,
  },
  {
    id: "f-usda-ready-007",
    name: "פדאי אורז",
    englishName: "Rice Pilaf",
    category: "ארוחות מוכנות",
    servingSize: "כוס (175 גרם)",
    calories: 214,
    protein: 4,
    carbs: 45,
    fat: 2,
    fiber: 1,
  },
  {
    id: "f-usda-ready-008",
    name: "קדאיף גבינה",
    englishName: "Knafeh with Cheese",
    category: "ארוחות מוכנות",
    servingSize: "100 גרם",
    calories: 360,
    protein: 8,
    carbs: 48,
    fat: 16,
    fiber: 1,
  },
  {
    id: "f-usda-ready-009",
    name: "קבב כבש",
    englishName: "Lamb Kebab Plate",
    category: "ארוחות מוכנות",
    servingSize: "מנה (200 גרם)",
    calories: 446,
    protein: 40,
    carbs: 12,
    fat: 27,
    fiber: 2,
  },
  {
    id: "f-usda-ready-010",
    name: "מוסקה",
    englishName: "Moussaka",
    category: "ארוחות מוכנות",
    servingSize: "מנה (200 גרם)",
    calories: 280,
    protein: 14,
    carbs: 16,
    fat: 18,
    fiber: 3,
  },

  // ── מוצרי אפייה וממרחים ──────────────────────────────────────────────────
  {
    id: "f-usda-bake-001",
    name: "דייסת שיבולת שועל בחלב",
    englishName: "Oatmeal with Milk",
    category: "ארוחות בוקר",
    servingSize: "קערה (280 גרם)",
    calories: 250,
    protein: 10,
    carbs: 38,
    fat: 7,
    fiber: 4,
  },
  {
    id: "f-usda-bake-002",
    name: "פרנץ׳ טוסט",
    englishName: "French Toast",
    category: "ארוחות בוקר",
    servingSize: "2 פרוסות (130 גרם)",
    calories: 290,
    protein: 10,
    carbs: 35,
    fat: 12,
    fiber: 1,
  },
  {
    id: "f-usda-bake-003",
    name: "פנקייק",
    englishName: "Pancakes (plain)",
    category: "ארוחות בוקר",
    servingSize: "3 פנקייקים (105 גרם)",
    calories: 271,
    protein: 8,
    carbs: 42,
    fat: 8,
    fiber: 1,
  },
  {
    id: "f-usda-bake-004",
    name: "וופל",
    englishName: "Waffle",
    category: "ארוחות בוקר",
    servingSize: "וופל (75 גרם)",
    calories: 218,
    protein: 6,
    carbs: 29,
    fat: 9,
    fiber: 1,
  },
  {
    id: "f-usda-bake-005",
    name: "קינמון רול",
    englishName: "Cinnamon Roll",
    category: "ממתקים וקינוחים",
    servingSize: "רול (100 גרם)",
    calories: 344,
    protein: 5,
    carbs: 55,
    fat: 12,
    fiber: 2,
  },
  {
    id: "f-usda-bake-006",
    name: "מאפין בלוברי",
    englishName: "Blueberry Muffin",
    category: "ממתקים וקינוחים",
    servingSize: "מאפין (113 גרם)",
    calories: 425,
    protein: 6,
    carbs: 62,
    fat: 18,
    fiber: 2,
  },
  {
    id: "f-usda-bake-007",
    name: "דונאט גלייז",
    englishName: "Glazed Doughnut",
    category: "ממתקים וקינוחים",
    servingSize: "דונאט (75 גרם)",
    calories: 302,
    protein: 5,
    carbs: 37,
    fat: 16,
    fiber: 1,
  },
  {
    id: "f-usda-bake-008",
    name: "טחינה גולמית",
    englishName: "Raw Tahini",
    category: "ממרחים",
    servingSize: "2 כפות (30 גרם)",
    calories: 178,
    protein: 5,
    carbs: 6,
    fat: 16,
    fiber: 2,
  },
  {
    id: "f-usda-bake-009",
    name: "ריבה תות",
    englishName: "Strawberry Jam",
    category: "ממרחים",
    servingSize: "כף (20 גרם)",
    calories: 49,
    protein: 0,
    carbs: 13,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bake-010",
    name: "נוטלה",
    englishName: "Nutella Chocolate Hazelnut Spread",
    category: "ממרחים",
    servingSize: "2 כפות (37 גרם)",
    calories: 200,
    protein: 3,
    carbs: 23,
    fat: 12,
    fiber: 1,
  },
  {
    id: "f-usda-bake-011",
    name: "ממרח שקדים",
    englishName: "Almond Spread",
    category: "ממרחים",
    servingSize: "2 כפות (32 גרם)",
    calories: 196,
    protein: 7,
    carbs: 7,
    fat: 18,
    fiber: 2,
  },
  {
    id: "f-usda-bake-012",
    name: "דבש",
    englishName: "Honey",
    category: "ממרחים",
    servingSize: "כף (21 גרם)",
    calories: 64,
    protein: 0,
    carbs: 17,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bake-013",
    name: "סירופ מייפל",
    englishName: "Maple Syrup",
    category: "ממרחים",
    servingSize: "כף (20 גרם)",
    calories: 52,
    protein: 0,
    carbs: 13,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-bake-014",
    name: "ממרח גבינה שמנה",
    englishName: "Cream Cheese Spread",
    category: "ממרחים",
    servingSize: "2 כפות (29 גרם)",
    calories: 101,
    protein: 2,
    carbs: 1,
    fat: 10,
    fiber: 0,
  },
  {
    id: "f-usda-bake-015",
    name: "גואקמולה",
    englishName: "Guacamole",
    category: "ממרחים",
    servingSize: "2 כפות (30 גרם)",
    calories: 50,
    protein: 1,
    carbs: 3,
    fat: 5,
    fiber: 2,
  },

  // ── מוצרי חלב מגוונים ────────────────────────────────────────────────────
  {
    id: "f-usda-dairy-001",
    name: "ריקוטה",
    englishName: "Ricotta Cheese",
    category: "גבינות",
    servingSize: "חצי כוס (123 גרם)",
    calories: 214,
    protein: 14,
    carbs: 4,
    fat: 16,
    fiber: 0,
  },
  {
    id: "f-usda-dairy-002",
    name: "גבינת מסקרפונה",
    englishName: "Mascarpone Cheese",
    category: "גבינות",
    servingSize: "2 כפות (28 גרם)",
    calories: 120,
    protein: 2,
    carbs: 1,
    fat: 12,
    fiber: 0,
  },
  {
    id: "f-usda-dairy-003",
    name: "גבינת הבלומי",
    englishName: "Halloumi Cheese",
    category: "גבינות",
    servingSize: "70 גרם",
    calories: 210,
    protein: 15,
    carbs: 1,
    fat: 17,
    fiber: 0,
  },
  {
    id: "f-usda-dairy-004",
    name: "גבינה כחולה",
    englishName: "Blue Cheese",
    category: "גבינות",
    servingSize: "28 גרם",
    calories: 100,
    protein: 6,
    carbs: 1,
    fat: 8,
    fiber: 0,
  },
  {
    id: "f-usda-dairy-005",
    name: "יוגורט איסלנדי",
    englishName: "Skyr (Icelandic Yogurt)",
    category: "יוגורט",
    servingSize: "150 גרם",
    calories: 120,
    protein: 17,
    carbs: 7,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-dairy-006",
    name: "יוגורט קוקוס",
    englishName: "Coconut Yogurt",
    category: "יוגורט",
    servingSize: "150 גרם",
    calories: 180,
    protein: 2,
    carbs: 15,
    fat: 12,
    fiber: 0,
  },
  {
    id: "f-usda-dairy-007",
    name: "שמנת חמוצה דלת שומן",
    englishName: "Low Fat Sour Cream",
    category: "גבינות",
    servingSize: "2 כפות (28 גרם)",
    calories: 28,
    protein: 1,
    carbs: 2,
    fat: 2,
    fiber: 0,
  },
  {
    id: "f-usda-dairy-008",
    name: "גבינת קממבר",
    englishName: "Camembert Cheese",
    category: "גבינות",
    servingSize: "28 גרם",
    calories: 85,
    protein: 6,
    carbs: 0,
    fat: 7,
    fiber: 0,
  },
  {
    id: "f-usda-dairy-009",
    name: "לבן",
    englishName: "Labneh (strained yogurt)",
    category: "גבינות",
    servingSize: "2 כפות (30 גרם)",
    calories: 50,
    protein: 3,
    carbs: 1,
    fat: 4,
    fiber: 0,
  },
  {
    id: "f-usda-dairy-010",
    name: "גבינת קרוט",
    englishName: "Cottage Cheese Low Fat 1%",
    category: "גבינות",
    servingSize: "100 גרם",
    calories: 72,
    protein: 12,
    carbs: 3,
    fat: 1,
    fiber: 0,
  },

  // ── תחליפי חלבון ─────────────────────────────────────────────────────────
  {
    id: "f-usda-protein-001",
    name: "שייק חלבון וויי",
    englishName: "Whey Protein Shake",
    category: "תחליפי ארוחה",
    servingSize: "מנה (35 גרם אבקה+240מ״ל מים)",
    calories: 130,
    protein: 25,
    carbs: 4,
    fat: 1,
    fiber: 0,
  },
  {
    id: "f-usda-protein-002",
    name: "שייק חלבון קזאין",
    englishName: "Casein Protein Shake",
    category: "תחליפי ארוחה",
    servingSize: "מנה (35 גרם אבקה+240מ״ל מים)",
    calories: 120,
    protein: 24,
    carbs: 5,
    fat: 1,
    fiber: 0,
  },
  {
    id: "f-usda-protein-003",
    name: "אבקת חלבון ביצה",
    englishName: "Egg White Protein Powder",
    category: "תחליפי ארוחה",
    servingSize: "28 גרם",
    calories: 110,
    protein: 25,
    carbs: 1,
    fat: 0,
    fiber: 0,
  },
  {
    id: "f-usda-protein-004",
    name: "בר חלבון 20+",
    englishName: "High Protein Bar 20g+",
    category: "תחליפי ארוחה",
    servingSize: "בר (65 גרם)",
    calories: 230,
    protein: 22,
    carbs: 25,
    fat: 7,
    fiber: 3,
  },
  {
    id: "f-usda-protein-005",
    name: "שייק הרבעת ארוחה",
    englishName: "Meal Replacement Shake",
    category: "תחליפי ארוחה",
    servingSize: "מנה (55 גרם אבקה)",
    calories: 220,
    protein: 18,
    carbs: 24,
    fat: 6,
    fiber: 3,
  },
];

const USDA_FOOD_SEARCH_URL = "https://fdc.nal.usda.gov/food-search?query=";

function addUsdaProvenance(food: FoodItem): FoodItem {
  const referenceName = food.englishName?.trim() || food.name.trim();

  return {
    ...food,
    nutritionReview: {
      status: "unreviewed",
      origin: "estimated",
      confidence: "medium",
      method: "existing-value",
      sources: [
        {
          name: `USDA FoodData Central — ${referenceName}`,
          url: `${USDA_FOOD_SEARCH_URL}${encodeURIComponent(referenceName)}`,
          kind: "usda",
          match: "same-food",
          valuesPer: "serving",
        },
      ],
      notes:
        "ערך seed המבוסס על נתוני ייחוס כלליים של USDA ומותאם למנה הרשומה כאן. זהו מקור השוואה בלבד, לא אימות של מוצר או תווית ספציפיים.",
    },
  };
}

export const USDA_FOOD_EXPANSION: FoodItem[] = USDA_FOOD_EXPANSION_SEED.map(addUsdaProvenance);
