/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as CoachClientsRouteImport } from './routes/coach.clients'
import { Route as CoachTrackingRouteImport } from './routes/coach.tracking'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises.$exerciseId'
import { Route as NutritionIndexRouteImport } from './routes/nutrition.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as SessionWorkoutIdRouteImport } from './routes/session.$workoutId'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as WorkoutsWorkoutIdRouteImport } from './routes/workouts.$workoutId'
import { Route as CoachClientsIndexRouteImport } from './routes/coach.clients.index'
import { Route as CoachClientsClientIdRouteImport } from './routes/coach.clients.$clientId'
import { Route as CoachTrackingIndexRouteImport } from './routes/coach.tracking.index'
import { Route as CoachTrackingClientIdRouteImport } from './routes/coach.tracking.$clientId'
import { Route as NutritionFoodsIndexRouteImport } from './routes/nutrition.foods.index'
import { Route as NutritionFoodsFoodIdRouteImport } from './routes/nutrition.foods.$foodId'
import { Route as ProgramsProgramIdDayIdRouteImport } from './routes/programs.$programId.$dayId'
import { Route as CoachClientsClientIdIndexRouteImport } from './routes/coach.clients.$clientId.index'
import { Route as CoachClientsClientIdNutritionRouteImport } from './routes/coach.clients.$clientId.nutrition'
import { Route as CoachClientsClientIdProgramRouteImport } from './routes/coach.clients.$clientId.program'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachClientsRoute = CoachClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => CoachRoute,
} as any)
const CoachTrackingRoute = CoachTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => CoachRoute,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionWorkoutIdRoute = SessionWorkoutIdRouteImport.update({
  id: '/session/$workoutId',
  path: '/session/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsWorkoutIdRoute = WorkoutsWorkoutIdRouteImport.update({
  id: '/workouts/$workoutId',
  path: '/workouts/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachClientsIndexRoute = CoachClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachClientsRoute,
} as any)
const CoachClientsClientIdRoute = CoachClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CoachClientsRoute,
} as any)
const CoachTrackingIndexRoute = CoachTrackingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachTrackingRoute,
} as any)
const CoachTrackingClientIdRoute = CoachTrackingClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => CoachTrackingRoute,
} as any)
const NutritionFoodsIndexRoute = NutritionFoodsIndexRouteImport.update({
  id: '/nutrition/foods/',
  path: '/nutrition/foods/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionFoodsFoodIdRoute = NutritionFoodsFoodIdRouteImport.update({
  id: '/nutrition/foods/$foodId',
  path: '/nutrition/foods/$foodId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdDayIdRoute = ProgramsProgramIdDayIdRouteImport.update({
  id: '/$dayId',
  path: '/$dayId',
  getParentRoute: () => ProgramsProgramIdRoute,
} as any)
const CoachClientsClientIdIndexRoute =
  CoachClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoachClientsClientIdRoute,
  } as any)
const CoachClientsClientIdNutritionRoute =
  CoachClientsClientIdNutritionRouteImport.update({
    id: '/nutrition',
    path: '/nutrition',
    getParentRoute: () => CoachClientsClientIdRoute,
  } as any)
const CoachClientsClientIdProgramRoute =
  CoachClientsClientIdProgramRouteImport.update({
    id: '/program',
    path: '/program',
    getParentRoute: () => CoachClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/coach/clients': typeof CoachClientsRouteWithChildren
  '/coach/tracking': typeof CoachTrackingRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/session/$workoutId': typeof SessionWorkoutIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/coach/': typeof CoachIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/coach/clients/$clientId': typeof CoachClientsClientIdRouteWithChildren
  '/coach/tracking/$clientId': typeof CoachTrackingClientIdRoute
  '/nutrition/foods/$foodId': typeof NutritionFoodsFoodIdRoute
  '/programs/$programId/$dayId': typeof ProgramsProgramIdDayIdRoute
  '/coach/clients/': typeof CoachClientsIndexRoute
  '/coach/tracking/': typeof CoachTrackingIndexRoute
  '/nutrition/foods/': typeof NutritionFoodsIndexRoute
  '/coach/clients/$clientId/nutrition': typeof CoachClientsClientIdNutritionRoute
  '/coach/clients/$clientId/program': typeof CoachClientsClientIdProgramRoute
  '/coach/clients/$clientId/': typeof CoachClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/session/$workoutId': typeof SessionWorkoutIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/coach': typeof CoachIndexRoute
  '/exercises': typeof ExercisesIndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/coach/tracking/$clientId': typeof CoachTrackingClientIdRoute
  '/nutrition/foods/$foodId': typeof NutritionFoodsFoodIdRoute
  '/programs/$programId/$dayId': typeof ProgramsProgramIdDayIdRoute
  '/coach/clients': typeof CoachClientsIndexRoute
  '/coach/tracking': typeof CoachTrackingIndexRoute
  '/nutrition/foods': typeof NutritionFoodsIndexRoute
  '/coach/clients/$clientId/nutrition': typeof CoachClientsClientIdNutritionRoute
  '/coach/clients/$clientId/program': typeof CoachClientsClientIdProgramRoute
  '/coach/clients/$clientId': typeof CoachClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/coach/clients': typeof CoachClientsRouteWithChildren
  '/coach/tracking': typeof CoachTrackingRouteWithChildren
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRouteWithChildren
  '/session/$workoutId': typeof SessionWorkoutIdRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/coach/': typeof CoachIndexRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/coach/clients/$clientId': typeof CoachClientsClientIdRouteWithChildren
  '/coach/tracking/$clientId': typeof CoachTrackingClientIdRoute
  '/nutrition/foods/$foodId': typeof NutritionFoodsFoodIdRoute
  '/programs/$programId/$dayId': typeof ProgramsProgramIdDayIdRoute
  '/coach/clients/': typeof CoachClientsIndexRoute
  '/coach/tracking/': typeof CoachTrackingIndexRoute
  '/nutrition/foods/': typeof NutritionFoodsIndexRoute
  '/coach/clients/$clientId/nutrition': typeof CoachClientsClientIdNutritionRoute
  '/coach/clients/$clientId/program': typeof CoachClientsClientIdProgramRoute
  '/coach/clients/$clientId/': typeof CoachClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/reset-password'
    | '/coach/clients'
    | '/coach/tracking'
    | '/exercises/$exerciseId'
    | '/programs/$programId'
    | '/session/$workoutId'
    | '/workouts/$workoutId'
    | '/coach/'
    | '/exercises/'
    | '/nutrition/'
    | '/programs/'
    | '/workouts/'
    | '/coach/clients/$clientId'
    | '/coach/tracking/$clientId'
    | '/nutrition/foods/$foodId'
    | '/programs/$programId/$dayId'
    | '/coach/clients/'
    | '/coach/tracking/'
    | '/nutrition/foods/'
    | '/coach/clients/$clientId/nutrition'
    | '/coach/clients/$clientId/program'
    | '/coach/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/exercises/$exerciseId'
    | '/programs/$programId'
    | '/session/$workoutId'
    | '/workouts/$workoutId'
    | '/coach'
    | '/exercises'
    | '/nutrition'
    | '/programs'
    | '/workouts'
    | '/coach/tracking/$clientId'
    | '/nutrition/foods/$foodId'
    | '/programs/$programId/$dayId'
    | '/coach/clients'
    | '/coach/tracking'
    | '/nutrition/foods'
    | '/coach/clients/$clientId/nutrition'
    | '/coach/clients/$clientId/program'
    | '/coach/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/reset-password'
    | '/coach/clients'
    | '/coach/tracking'
    | '/exercises/$exerciseId'
    | '/programs/$programId'
    | '/session/$workoutId'
    | '/workouts/$workoutId'
    | '/coach/'
    | '/exercises/'
    | '/nutrition/'
    | '/programs/'
    | '/workouts/'
    | '/coach/clients/$clientId'
    | '/coach/tracking/$clientId'
    | '/nutrition/foods/$foodId'
    | '/programs/$programId/$dayId'
    | '/coach/clients/'
    | '/coach/tracking/'
    | '/nutrition/foods/'
    | '/coach/clients/$clientId/nutrition'
    | '/coach/clients/$clientId/program'
    | '/coach/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRouteWithChildren
  SessionWorkoutIdRoute: typeof SessionWorkoutIdRoute
  WorkoutsWorkoutIdRoute: typeof WorkoutsWorkoutIdRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  NutritionFoodsFoodIdRoute: typeof NutritionFoodsFoodIdRoute
  NutritionFoodsIndexRoute: typeof NutritionFoodsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/clients': {
      id: '/coach/clients'
      path: '/clients'
      fullPath: '/coach/clients'
      preLoaderRoute: typeof CoachClientsRouteImport
      parentRoute: typeof CoachRoute
    }
    '/coach/tracking': {
      id: '/coach/tracking'
      path: '/tracking'
      fullPath: '/coach/tracking'
      preLoaderRoute: typeof CoachTrackingRouteImport
      parentRoute: typeof CoachRoute
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$workoutId': {
      id: '/session/$workoutId'
      path: '/session/$workoutId'
      fullPath: '/session/$workoutId'
      preLoaderRoute: typeof SessionWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$workoutId': {
      id: '/workouts/$workoutId'
      path: '/workouts/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/clients/': {
      id: '/coach/clients/'
      path: '/'
      fullPath: '/coach/clients/'
      preLoaderRoute: typeof CoachClientsIndexRouteImport
      parentRoute: typeof CoachClientsRoute
    }
    '/coach/clients/$clientId': {
      id: '/coach/clients/$clientId'
      path: '/$clientId'
      fullPath: '/coach/clients/$clientId'
      preLoaderRoute: typeof CoachClientsClientIdRouteImport
      parentRoute: typeof CoachClientsRoute
    }
    '/coach/tracking/': {
      id: '/coach/tracking/'
      path: '/'
      fullPath: '/coach/tracking/'
      preLoaderRoute: typeof CoachTrackingIndexRouteImport
      parentRoute: typeof CoachTrackingRoute
    }
    '/coach/tracking/$clientId': {
      id: '/coach/tracking/$clientId'
      path: '/$clientId'
      fullPath: '/coach/tracking/$clientId'
      preLoaderRoute: typeof CoachTrackingClientIdRouteImport
      parentRoute: typeof CoachTrackingRoute
    }
    '/nutrition/foods/': {
      id: '/nutrition/foods/'
      path: '/nutrition/foods'
      fullPath: '/nutrition/foods/'
      preLoaderRoute: typeof NutritionFoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/foods/$foodId': {
      id: '/nutrition/foods/$foodId'
      path: '/nutrition/foods/$foodId'
      fullPath: '/nutrition/foods/$foodId'
      preLoaderRoute: typeof NutritionFoodsFoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/$dayId': {
      id: '/programs/$programId/$dayId'
      path: '/$dayId'
      fullPath: '/programs/$programId/$dayId'
      preLoaderRoute: typeof ProgramsProgramIdDayIdRouteImport
      parentRoute: typeof ProgramsProgramIdRoute
    }
    '/coach/clients/$clientId/': {
      id: '/coach/clients/$clientId/'
      path: '/'
      fullPath: '/coach/clients/$clientId/'
      preLoaderRoute: typeof CoachClientsClientIdIndexRouteImport
      parentRoute: typeof CoachClientsClientIdRoute
    }
    '/coach/clients/$clientId/nutrition': {
      id: '/coach/clients/$clientId/nutrition'
      path: '/nutrition'
      fullPath: '/coach/clients/$clientId/nutrition'
      preLoaderRoute: typeof CoachClientsClientIdNutritionRouteImport
      parentRoute: typeof CoachClientsClientIdRoute
    }
    '/coach/clients/$clientId/program': {
      id: '/coach/clients/$clientId/program'
      path: '/program'
      fullPath: '/coach/clients/$clientId/program'
      preLoaderRoute: typeof CoachClientsClientIdProgramRouteImport
      parentRoute: typeof CoachClientsClientIdRoute
    }
  }
}

interface CoachClientsClientIdRouteChildren {
  CoachClientsClientIdNutritionRoute: typeof CoachClientsClientIdNutritionRoute
  CoachClientsClientIdProgramRoute: typeof CoachClientsClientIdProgramRoute
  CoachClientsClientIdIndexRoute: typeof CoachClientsClientIdIndexRoute
}

const CoachClientsClientIdRouteChildren: CoachClientsClientIdRouteChildren = {
  CoachClientsClientIdNutritionRoute: CoachClientsClientIdNutritionRoute,
  CoachClientsClientIdProgramRoute: CoachClientsClientIdProgramRoute,
  CoachClientsClientIdIndexRoute: CoachClientsClientIdIndexRoute,
}

const CoachClientsClientIdRouteWithChildren =
  CoachClientsClientIdRoute._addFileChildren(CoachClientsClientIdRouteChildren)

interface CoachClientsRouteChildren {
  CoachClientsClientIdRoute: typeof CoachClientsClientIdRouteWithChildren
  CoachClientsIndexRoute: typeof CoachClientsIndexRoute
}

const CoachClientsRouteChildren: CoachClientsRouteChildren = {
  CoachClientsClientIdRoute: CoachClientsClientIdRouteWithChildren,
  CoachClientsIndexRoute: CoachClientsIndexRoute,
}

const CoachClientsRouteWithChildren = CoachClientsRoute._addFileChildren(
  CoachClientsRouteChildren,
)

interface CoachTrackingRouteChildren {
  CoachTrackingClientIdRoute: typeof CoachTrackingClientIdRoute
  CoachTrackingIndexRoute: typeof CoachTrackingIndexRoute
}

const CoachTrackingRouteChildren: CoachTrackingRouteChildren = {
  CoachTrackingClientIdRoute: CoachTrackingClientIdRoute,
  CoachTrackingIndexRoute: CoachTrackingIndexRoute,
}

const CoachTrackingRouteWithChildren = CoachTrackingRoute._addFileChildren(
  CoachTrackingRouteChildren,
)

interface CoachRouteChildren {
  CoachClientsRoute: typeof CoachClientsRouteWithChildren
  CoachTrackingRoute: typeof CoachTrackingRouteWithChildren
  CoachIndexRoute: typeof CoachIndexRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachClientsRoute: CoachClientsRouteWithChildren,
  CoachTrackingRoute: CoachTrackingRouteWithChildren,
  CoachIndexRoute: CoachIndexRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface ProgramsProgramIdRouteChildren {
  ProgramsProgramIdDayIdRoute: typeof ProgramsProgramIdDayIdRoute
}

const ProgramsProgramIdRouteChildren: ProgramsProgramIdRouteChildren = {
  ProgramsProgramIdDayIdRoute: ProgramsProgramIdDayIdRoute,
}

const ProgramsProgramIdRouteWithChildren =
  ProgramsProgramIdRoute._addFileChildren(ProgramsProgramIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  ProgramsProgramIdRoute: ProgramsProgramIdRouteWithChildren,
  SessionWorkoutIdRoute: SessionWorkoutIdRoute,
  WorkoutsWorkoutIdRoute: WorkoutsWorkoutIdRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  NutritionIndexRoute: NutritionIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  NutritionFoodsFoodIdRoute: NutritionFoodsFoodIdRoute,
  NutritionFoodsIndexRoute: NutritionFoodsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
